<nav>
    <?php if ($this->isAlbum): ?>
        <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index'), null, true) ?>"
           class="bouton1">
            <?php echo $this->translate->_('retour_albums'); ?>
        </a>
    <?php endif; ?>
    <?php if ($this->isRole(Application_Model_Acl::ROLE_MEMBRE) || $this->isAdmin()): ?>
        <?php if (!$this->isAlbum): ?>
            <?php if ($this->isAdmin() && $this->adminAlbum): ?>
                <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'supprimeralbum'), null, true) ?>" 
                   id="lnkSupprimer"
                   class="bouton1">
                    Supprimer album(s)
                </a>
                <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'ajouter'), null, true) ?>" 
                   id="lnkAjouter"
                   class="bouton1">
                    Ajouter un album
                </a>
                <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index'), null, true) ?>" 
                   class="bouton1"
                   style="float: right">
                    Retour à la galerie
                </a>
            <form method="POST" id="frmAjouter" style="display:none;">
                Nom du nouvel album&nbsp;: <input type="text" id="nom" name="nom"/>
            </form>
        <?php else: ?>
            <a id="lnkSubmit"
               href="<?= $this->url(array('controller' => 'galerie', 'action' => 'soumettre'), null, true) ?>" 
               class="bouton1">
                <?php echo $this->translate->_('soumettre_image'); ?>
            </a>
            <?php if ($this->isAdmin()): ?>
                <a id="lnkAdmin" 
                   href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index', 'admin' => true), null, true) ?>" 
                   class="bouton1"
                   style="float: right">
                    Administration des albums
                </a>
            <?php endif; ?>
        <?php endif; ?>

    <?php else: ?>
        <?php if ($this->isAdmin()): ?>
            <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index', 'id' => $this->album->id, 'admin' => true), null, true) ?>" 
               style="float: right"
               class="bouton1">
                Administrer cet album
            </a>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
</nav>

<?php if ($this->isAdmin() && $this->adminAlbum && $this->isAlbum): ?>
<div style="margin-top:20px;">
    <div class="box">
        <h1 class="titreNews">Action pour les photos/vidéos sélectionné&nbsp;:</h1>
        <a id="lnkDeleteElements" class="bouton1" href="<?= $this->url(array('controller'=>'galerie', 'action'=>'supprimerelements'), null, true); ?>" title="Suppression d'éléments">Supprimer</a>
        <a id="lnkMove" class="bouton1" href="javascript:return false;">Déplacer</a>
        <div style="display: none; margin-top: 10px;" id="actions">
            Vers l'album&nbsp;:
            <select id="sltAlbumDestination">
                <?php foreach ($this->albums as $a): ?>
                    <option value="<?= $a->id ?>"><?= $a->nom ?></option>
                <?php endforeach; ?>
            </select>
            <a id="lnkValidMove" href="<?= $this->url(array('controller'=>'galerie', 'action'=>'deplacer'), null, true); ?>" class="bouton1">Valider</a>
        </div>
    </div>
</div>
<?php endif; ?>

<section class="totalBox">
    <div class="box">
        <h1 class="titreNews">
            <?= $this->titre; ?>
        </h1>
        <?php if ($this->isAlbum): ?>
           <div class="fb_button social_button">
                <a  target="_blank"
                    href="https://www.facebook.com/share.php?u=<?=
                        $_SERVER['HTTP_HOST'].$this->url(array(
                   'controller' => 'galerie', 'action' => 'index', 'id' => $this->album->id
                ))
            ?>">
                   <i class="logo logo_fb"></i>
                   <?php echo $this->translate->_('fb_partager'); ?>
                </a>
            </div>
            <?php $twitter_link_args='via=Sesquidistus&source=tweetbutton' ?>
            <?php $twitter_link_args.= '&original_referer='.urlencode($_SERVER['HTTP_HOST'] . $this->url(array('controller' => 'galerie', 'action' => 'index', 'id' => $this->album->id))) ?>
            <?php $twitter_link_args.= '&text='.urlencode('Nouvel album photos et vidéos: '.$this->album->nom) ?>
            <div class="twitter_button social_button">
	            <a  target="_blank"
	                href="https://twitter.com/intent/tweet?<?= $twitter_link_args ?>">
	                <img alt="Partager ce tutoriel sur Twitter" src="/images/social/ico-tweeter.png" width="65" height="20"/>
	            </a>
	        </div>
        <?php endif; ?>
        <?php if ($this->isAdmin() && $this->adminAlbum): ?>
            <form method="POST" id="frmModifier">
            <?php if ($this->isAlbum): ?>
                <input type="hidden" name="idAlbum" value="<?= $this->album->id ?>" />
                <input type="hidden" name="albumDestination" id="albumDestination" />
            <?php endif; ?>
            <?php endif; ?>
            <table id="albumContainer" class="container">
                <?php $nbColonne = 4; ?>
                <?php for ($i = 0; $i < count($this->images); $i++): ?>
                    <?php if ($i % $nbColonne == 0): ?>
                        <tr>
                        <?php endif; ?>
                        <?php
                        if ($this->isAlbum) {
                            $element = $this->images[$i];
                            $href = $this->images[$i]->getNomWithPath();
                        } else {
                            $element = $this->albums[$i];
                            $href = $this->url(array('controller' => 'galerie', 'action' => 'index', 'id' => $element->id), null, true);
                        }
                        ?>
                        <td id="<?= $element->id; ?>" title="<?= $element->nom; ?>">
                            <div class="bouton4 albumBox">
                                <div class="albumImg" style="height: 120px;">
                                    <a href="<?= $href; ?>" class="<?php
                    if ($this->isAlbum) {
                        echo 'photo';
                    }
                        ?>">
                                        <img src="<?= $this->images[$i]->getNomWithMiniPath(); ?>" 
                                             alt="<?php
                                   if ($this->isAlbum) {
                                       echo 'Image ';
                                   }
                        ?><?= $element->nom; ?>"
                                             style="max-height: 90px; max-width: 120px;"/>
                                    </a>
                                </div>
                                <div style="padding-top: 15px;">
                                    <span class="spnNom">
                                        <a href="<?= $href; ?>" class="<?php
                                         if ($this->isAlbum) {
                                             echo 'photo';
                                         }
                        ?>">
                                               <?= $this->shortText($element->nom, 17); ?>
                                        </a>
                                        <?php if ($this->isAdmin() && $this->adminAlbum): ?>
                                            <input type="checkbox" value="<?= $element->id; ?>" name="elements[]"/>
                                        <?php endif; ?>
                                    </span>
                                </div>
                            </div>
                        </td>
                        <?php if ($i % $nbColonne == ($nbColonne - 1)): ?>
                        </tr>
                    <?php endif; ?>
                <?php endfor; ?>
            </table>
            <?php if (isset($this->videos)): ?>
                <table id="albumVideosContainer" class="container">
                    <?php $nbColonne = 4; ?>
                    <?php for ($i = 0; $i < count($this->videos); $i++): ?>
                        <?php if ($i % $nbColonne == 0): ?>
                            <tr>
                            <?php endif; ?>
                            <?php $video = $this->videos[$i]; ?>
                            <td id="<?= $video->id; ?>" title="<?= $video->titre; ?>" class="video">
                                <div class="videoEmbeddedCode" title="<?= $video->titre; ?>" style="display:none;">
                                    <?= $video->getEmbeddedCode(); ?>
                                    <?php
                                    $description = $video->getDescription();
                                    if (!empty($description)):
                                        ?>
                                        <div class="bouton6">
                                            <?= $description; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="bouton4 albumBox">
                                    <div class="albumImg" style="height: 120px;">
                                        <img src="<?= $video->getImage(); ?>" 
                                             alt="<?= $video->titre; ?>"
                                             style="max-height: 90px; max-width: 120px;"/>
                                    </div>
                                    <div style="padding-top: 15px;">
                                        <span class="spnNom">
                                            <?= $this->shortText($video->titre, 17); ?>
                                            <?php if ($this->isAdmin() && $this->adminAlbum): ?>
                                            <input type="checkbox" value="<?= $video->id; ?>" id="video<?= $video->id; ?>" name="videos[]" class="chkAdminAlbum" />
                                            <?php endif; ?>
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <?php if ($i % $nbColonne == ($nbColonne - 1)): ?>
                            </tr>
                        <?php endif; ?>
                    <?php endfor; ?>
                </table>
            <?php endif; ?>
            <?php if ($this->isAdmin() && $this->adminAlbum): ?>
            </form>
        <?php endif; ?>
    </div>
</section>

<div id="dialog" style="display:none;"></div>
