<p>
    <?php if ($this->albums === null): ?>
    <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index'), null, true) ?>"
       class="bouton1">
        Retour aux albums
    </a>
    <?php endif; ?>
    <?php if ($this->isRole(Application_Model_Acl::ROLE_MEMBRE) || $this->isAdmin()): ?>
        <?php if ($this->albums !== null): ?>
            <?php if ($this->isAdmin() && $this->adminAlbum): ?>
                <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'supprimer'), null, true) ?>" 
                   id="lnkSupprimer"
                   class="bouton1">
                    Supprimer album(s)
                </a>
                <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'ajouter'), null, true) ?>" 
                   id="lnkAjouter"
                   class="bouton1">
                    Ajouter un album
                </a>
                <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index'), null, true) ?>" 
                   class="bouton1"
                   style="float: right">
                    Retour à la galerie
                </a>
            <form method="POST" id="frmAjouter" style="display:none;">
                Nom du nouvel album&nbsp;: <input type="text" id="nom" name="nom">
            </form>
        <?php else: ?>
            <a id="lnkSubmit"
               href="<?= $this->url(array('controller' => 'galerie', 'action' => 'soumettre')) ?>" 
               class="bouton1">
                Soumettre une image
            </a>
            <?php if ($this->isAdmin()): ?>
                <a id="lnkAdmin" 
                   href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index', 'admin' => true)) ?>" 
                   class="bouton1"
                   style="float: right">
                    Administration des albums
                </a>
            <?php endif; ?>
        <?php endif; ?>

    <?php else: ?>
        <?php if ($this->isAdmin()): ?>
            <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'administration', 'id' => $this->album->id)) ?>" 
               style="float: right"
               class="bouton1">
                Administrer cet album
            </a>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
</p>

<div class="totalBox">
    <div class="box">
        <div class="titreNews"><?= $this->titre; ?></div>
        <?php if ($this->isAdmin() && $this->adminAlbum): ?>
            <form method="POST" id="frmSupprimer">
            <?php endif; ?>
            <table id="albumContainer" class="container">
                <?php $nbColonne = 4; ?>
                <?php for ($i = 0; $i < count($this->images); $i++): ?>
                    <?php if ($i % $nbColonne == 0): ?>
                        <tr>
                        <?php endif; ?>
                        <?php
                        if ($this->albums === null) {
                            $element = $this->images[$i];
                            $href = $this->images[$i]->getNomWithPath();
                        } else {
                            $element = $this->albums[$i];
                            $href = $this->url(array('controller' => 'galerie', 'action' => 'index', 'id' => $element->id));
                        }
                        ?>
                        <td id="<?= $element->id; ?>" title="<?= $element->nom; ?>">
                            <div class="bouton4 albumBox">
                                <div style="height: 120px;">
                                    <a href="<?= $href; ?>" class="<?php
                    if ($this->isAlbum) {
                        echo 'photo';
                    }
                    ?>">
                                        <img src="<?= $this->images[$i]->getNomWithMiniPath(); ?>" 
                                             alt="<?php
                                         if ($this->isAlbum) {
                                             echo 'Image ';
                                         }
                                         ?><?= $element->nom; ?>" />
                                    </a>
                                </div>
                                <div style="padding-top: 15px;">
                                    <span class="spnNom">
                                        <a href="<?= $href; ?>" class="<?php
                                         if ($this->isAlbum) {
                                             echo 'photo';
                                         }
                        ?>">
    <?= $this->shortText($element->nom, 17); ?>
                                        </a>
                        <?php if ($this->isAdmin() && $this->adminAlbum): ?>
                                            <input type="checkbox" value="<?= $element->id; ?>" name="del[]">
                    <?php endif; ?>
                                    </span>
                                </div>
                            </div>
                        </td>
                    <?php if ($i % $nbColonne == ($nbColonne - 1)): ?>
                        </tr>
                    <?php endif; ?>
                <?php endfor; ?>
            </table>
                    <?php if (isset($this->videos)): ?>
                <table id="albumVideosContainer" class="container">
    <?php $nbColonne = 4; ?>
                                <?php for ($i = 0; $i < count($this->videos); $i++): ?>
                                    <?php if ($i % $nbColonne == 0): ?>
                            <tr>
                                    <?php endif; ?>
                                        <?php $video = $this->videos[$i]; ?>
                            <td id="<?= $video->id; ?>" title="<?= $video->titre; ?>" class="video">
                                <div class="videoEmbeddedCode" title="<?= $video->titre; ?>" style="display:none;">
                                    <?= $video->getEmbeddedCode(); ?>
        <?php $description = $video->getDescription();
        if (!empty($description)):
            ?>
                                        <div class="bouton6">
            <?= $description; ?>
                                        </div>
        <?php endif; ?>
                                </div>
                                <div class="bouton4 albumBox">
                                    <div style="height: 120px;">
                                        <img src="<?= $video->getImage(); ?>" 
                                             alt="<?= $video->titre; ?>" />
                                    </div>
                                    <div style="padding-top: 15px;">
                                        <span class="spnNom">
                            <?= $this->shortText($video->titre, 17); ?>
                            <?php if ($this->isAdmin() && $this->adminAlbum): ?>
                                                <input type="checkbox" value="<?= $video->id; ?>" name="delVideo[]">
                        <?php endif; ?>
                                        </span>
                                    </div>
                                </div>
                            </td>
                <?php if ($i % $nbColonne == ($nbColonne - 1)): ?>
                            </tr>
        <?php endif; ?>
    <?php endfor; ?>
                </table>
<?php endif; ?>
<?php if ($this->isAdmin() && $this->adminAlbum): ?>
            </form>
<?php endif; ?>
    </div>
</div>

<div id="dialog" style="display:none;"></div>