<div class="totalBox">
    <p>
        <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index')); ?>" class="bouton1">
            <?php echo $this->translate->_('retour_albums'); ?>
        </a>
    </p>
    <div class="box">
        <h2 class="titreNews"><?php echo $this->translate->_('soumettre_image'); ?></h2>
        <form action="<?= $this->url(array('controller' => 'galerie', 'action' => 'upload')); ?>" method="post" enctype="multipart/form-data" id="frmPhoto">
            <label for="sltAlbum"><?php echo $this->translate->_('album'); ?>:</label>
            <select id="sltAlbum" name="sltAlbum">
                <option value="" selected="selected"><?php echo $this->translate->_('selectionner_album'); ?></option>
                <option value="">------------------</option>
                <?php foreach ($this->albums as $album): ?>
                    <option value="<?= $album->id ?>"><?= $album->nom ?></option>
                <?php endforeach; ?>
            </select>
            <div id="dropbox" style="display: none;"></div>
        </form>
        <div style="position: absolute; top: 0px; right: 0px;">
            <a target="_blank" href="/doc/doc_galerie/doc_galerie.html#submit_photo">
                <img style="width: 25px;" alt="aide" src="/images/help.png"/>
            </a>
        </div>
    </div>
    <br />
    <div class="box">
        <h2 class="titreNews"><?php echo $this->translate->_('soumettre_video'); ?></h2>
        <form action="<?= $this->url(array('controller' => 'galerie', 'action' => 'soumettre')) ?>" 
              method="post" enctype="multipart/form-data" id="frmAddVideo">
            <label for="sltAlbumVideo"><?php echo $this->translate->_('album'); ?>:</label>
            <select id="sltAlbumVideo" name="sltAlbumVideo">
                <option value="" selected="selected"><?php echo $this->translate->_('selectionner_album'); ?></option>
                <option value="">------------------</option>
                <?php foreach ($this->albums as $album): ?>
                    <option value="<?= $album->id ?>"><?= $album->nom ?></option>
                <?php endforeach; ?>
            </select>
            <span style="font-style:italic">(Youtube, Dailymotion et Viméo)</span>
            <p id="urlVideo" style="display: none;">
                <label for="lienVideo"><?php echo $this->translate->_('entrez_url'); ?>:</label>
                <input type="text" id="lienVideo" name="lienVideo" />
                <input type="submit" class="bouton1" value="Envoyer" style="float: right;"/>
            </p>
        </form>
        <div style="position: absolute; top: 0px; right: 0px;">
            <a target="_blank" href="./doc/doc_galerie/doc_galerie.html#submit_video">
                <img style="width: 25px;" alt="aide" src="/images/help.png"/>
            </a>
        </div>
    </div>
</div>
