<?php $article = $this->article; ?>
<article class="totalBox" itemscope itemtype="http://schema.org/NewsArticle">
    <div class="box">
        <h2 class="titreNews">
            <span itemprop="name"><?= $this->escape($article->titre) ?></span>
            <?php if ($this->isAdmin()): ?>
                <a href="<?= $this->url(array('controller' => 'article', 'action' => 'ecrire', 'id' => $article->id)); ?>">
                    <img class="editArticle" src="/images/edit.png" alt="Modifier" title="Modifier"/>
                </a>
                <a href="<?= $this->url(array('controller' => 'article', 'action' => 'supprimer', 'id' => $article->id)); ?>" class="supprimer">
                    <img class="editArticle" src="/images/del.png" alt="Supprimer" title="Supprimer"/>
                </a>
            <?php endif; ?>
        </h2>
        <div itemprop="articleBody"><?php echo $article->contenu ?></div>
        <div style="margin-top:30px; margin-bottom: 7px;">
            <?php
            if ($article->author !== null) {
                $author = 'par <span itemprop="author">'.$article->author->login.'</span>';
            } else {
                $author = '';
            }
            ?>
            <span class="note" style="text-align: left;" itemscope itemtype="http://schema.org/Person">
                Article créé <?= $author ?> le <?= $this->escape($article->date->get('dd/MM/YYYY')) ?>
                <meta itemprop="dateCreated" content="<?= $this->escape($article->date->get(Zend_Date::ISO_8601)) ?>" />
            </span>
            <div class="fb_button" style="float:right;">
                <a  target="_blank"
                    href="https://www.facebook.com/share.php?u=<?= $_SERVER['HTTP_HOST'] . $this->url(array('controller' => 'index', 'action' => 'index', 'id_article' => $article->id)) ?>">
                    <i class="logo logo_fb"></i>
                    Partager
                </a>
            </div>
        </div>
    </div>
</article>
