<?php $article = $this->article; ?>
<article class="totalBox">
    <div class="box">
        <div class="titreNews">
            <?= $this->escape($article->titre) ?>
            <?php if ($this->isAdmin()): ?>
                <a href="<?= $this->url(array('controller' => 'article', 'action' => 'ecrire', 'id' => $article->id)); ?>">
                    <img class="editArticle" src="/images/edit.png" alt="Modifier" title="Modifier"/>
                </a>
                <a href="<?= $this->url(array('controller' => 'article', 'action' => 'supprimer', 'id' => $article->id)); ?>" class="supprimer">
                    <img class="editArticle" src="/images/del.png" alt="Supprimer" title="Supprimer"/>
                </a>
            <?php endif; ?>
        </div>
        <div><?php echo $article->contenu ?></div>
        <div style="margin-top:30px; margin-bottom: 7px;">
            <?php
            if ($article->author !== null) {
                $author = 'par '.$article->author->login;
            } else {
                $author = '';
            }
            ?>
            <span class="note" style="text-align: left;">Article créé <?= $author ?> le <?php echo $this->escape($article->date->get('dd/MM/YYYY')) ?></span>
            <div class="fb_button" style="float:right;">
                <a  target="_blank"
                    href="https://www.facebook.com/share.php?u=<?= $_SERVER['HTTP_HOST'] . $this->url(array('controller' => 'index', 'action' => 'index', 'id_article' => $article->id)) ?>">
                    <i class="thumb"></i>
                    Partager
                </a>
            </div>
        </div>
    </div>
</article>