<form id="frmEcrire" style="margin-bottom:200px;" method="POST" action="<?= $this->url(array('controller' => 'article', 'action' => 'ecrire')) ?>">
    <div style="width:700px;margin:0 auto;">
        <h3>
            Création d'un article pour l'évènement&nbsp;: 
            <select id="sltEvents" name="idEvent">
                <option value="null" selected="selected">Aucun</option>
                <option value="-1">Autre...</option>
            </select> 
            <input type="hidden" value="<?= $this->url(array('controller' => 'evenements', 'action' => 'list')) ?>" id="urlList" />
        </h3>
        <div style="display:inline;padding:8px 5px;" class="bouton2">
            <input type="text" maxlength="50" size="50" name="titre" value="<?= '' ?>" class="required" />
            <span>(Titre de l'article)</span>
        </div>
        <div id="tinyMceBox" style="margin-top:30px;">
            <textarea id="contenu" name="contenu" rows="15" cols="80" class="tinymce">
                <?= '' ?>
            </textarea>
        </div>
        <input class="bouton1" style="float:right" id="buttonValider" type="submit" value="Valider l'article" />
    </div>
</form>
<div id="dialog" style="display:none">
    <div style="display:inline;padding:8px 5px;" class="bouton2">
        <input type="text" id="txtEvent" />
    </div>
</div>