<?php $contact = $this->contact ?>
<div class="totalBox"> 
    <div class="box" style="margin-bottom:20px">
        <div class="titreNews">Comment nous contacter&nbsp;?</div>
        <p><strong><?= $contact->prenom ?> <?= $contact->nom ?></strong></p>
        <p><strong><span style="color: #0000ff;"><?= $contact->email ?></span></strong></p>
        <?php $tel = $contact->telephone; ?>
        <?php if (!empty($tel)): ?>
            <p>Tél&nbsp;: <?= $contact->telephone ?></p>
        <?php endif; ?>
    </div>
</div>
