<div id="globalMini">
    <?php if ($this->isAdmin()): ?>
        <div class="totalBox" style="text-align:center;">
            <a href="<?= $this->url(array('controller' => 'article', 'action' => 'ecrire')) ?>" class="bouton1">&Eacute;crire un nouvel article</a>
        </div>
    <?php endif; ?>
    <?php if (!empty($this->nextTraining)): ?>
        <div id="nextTraining" class="totalBox">
            <div class="box" style="min-height:150px;">
                <img style="position:absolute; right:2px; bottom:1px" src="/images/silhouette3_mini.gif" />
                <div class="titreNews">Prochain entraînement</div>
                <p style="text-align:left;"> 
                <div style="color:#bc0101; margin-bottom:10px; font-size:11px"><?= $this->escape($this->nextTraining->titre); ?></div>
                <table>
                    <tr>
                        <td style="color:#555">Date&nbsp;:</td>
                        <td><?= $this->escape($this->nextTraining->date->get('dd/MM/YYYY')) ?></td>
                    </tr>
                    <?php if ($this->nextTraining->lieu !== ''): ?>
                        <tr>
                            <td style="color:#555">Lieu&nbsp;:</td>
                            <td>
                                <?php
                                if (is_string($this->nextTraining->lieu)) {
                                    echo $this->escape($this->nextTraining->lieu);
                                } else {
                                    echo $this->escape($this->nextTraining->lieu->nom);
                                    ?>
                                    <a title="Google maps" href="<?= $this->url(array('controller' => 'club', 'id' => 5)) ?>/#map<?= $this->nextTraining->lieu->id ?>">
                                        <img src="/images/loupe.png"/>
                                    </a>
                                    <?php
                                }
                                ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($this->nextTraining->horaire_debut !== ''): ?>
                        <tr>
                            <td style="color:#555">Début&nbsp;:</td>
                            <td><?php echo $this->escape($this->nextTraining->horaire_debut) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($this->nextTraining->horaire_fin !== ''): ?>
                        <tr>
                            <td style="color:#555">Fin&nbsp;:</td>
                            <td><?php echo $this->escape($this->nextTraining->horaire_fin) ?></td>
                        </tr>
                    <?php endif; ?>
                </table>
                </p>
            </div>
        </div>
    <?php endif; ?>
    <?php if (!empty($this->nextTournoi)): ?>
        <div id="nextTournoi" class="totalBox">	
            <div class="box" style="min-height:150px;">
                <img style="position:absolute; right:2px; bottom:1px" src="/images/silhouette4.gif" />
                <div class="titreNews">Prochain tournoi</div>
                <p style="text-align:left;"> 
                <div style="color:#bc0101; margin-bottom:10px; font-size:11px;"><?= $this->escape($this->nextTournoi->titre) ?> </div>
                <table style="font-size:11px">
                    <tr>
                        <td style="color:#555">Date&nbsp;:</td>
                        <td><span id="dateNextTournoi"><?= $this->escape($this->nextTournoi->date->get('dd/MM/YYYY')) ?></span></td>
                    </tr>
                    <tr>
                        <td style="color:#555">Lieu&nbsp;:</td>
                        <td>
                            <?php
                            if (is_string($this->nextTournoi->lieu)) {
                                echo $this->escape($this->nextTournoi->lieu);
                            } else {
                                echo $this->escape($this->nextTournoi->lieu->nom);
                            }
                            ?>
                        </td>
                    </tr>
                    <?php if (isset($this->nextTournoi->horaire_debut)): ?>
                        <tr>
                            <td style="color:#555">Début&nbsp;:</td>
                            <td><?= $this->escape($this->nextTournoi->horaire_debut) ?></td>
                        </tr>
                    <?php endif ?>
                    <?php if (isset($this->nextTournoi->horaire_fin)): ?>
                        <tr>
                            <td style="color:#555">Fin&nbsp;:</td>
                            <td><?= $this->escape($this->nextTournoi->horaire_fin) ?></td>
                        </tr>
                    <?php endif ?>
                </table>
                </p>
            </div>
        </div>
    <?php endif ?>
    <?php if (!empty($this->video)): ?>
        <div id="newVideo" class="totalBox">
            <div class="box">
                <div class="titreNews">Vidéo du moment</div>
                <a href="#" class="video">
                    <div style="position:relative;">
                        <img style="width:170px;" src="<?= $this->video->getImage() ?>" alt="<?= $this->video->titre ?>" title="<?= $this->video->titre ?>" />
                    </div>
                    <div style="position:absolute; margin-top:-92px; margin-left:60px">
                        <img style="width:50px;" src="/images/play.png" alt="<?= $this->video->titre ?>" title="<? $this->video->titre ?>"/>
                    </div>
                    <div class="videoEmbeddedCode" title="<?= $this->video->titre; ?>" style="display:none;">
                        <?= $this->video->getEmbeddedCode(); ?>
                        <?php
                        $description = $this->video->getDescription();
                        if (!empty($description)):
                            ?>
                            <div class="cartouche">
                                <?= $description; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </a>
            </div>
        </div>
        <div id="dialogVideo" style="display:none;"></div>
    <?php endif ?>
    <div class="totalBox">
        <div class="box">
            <div class="titreNews">Retrouvez-nous</div>
            <div style="text-align: center;">
                <a href="https://www.facebook.com/pages/Sesquidistus-Strasbourg-France/265227373552209">
                    <img src="/images/social/facebook-32.png" style="height: 30px;" alt="Facebook" title="Facebook" />
                </a>
                <a href="<?= $this->url(array('controller'=>'index', 'action'=>'rss')); ?>">
                    <img src="/images/social/rss-30.png" style="height: 30px;" alt="Flux RSS" title="Flux RSS" />
                </a>
            </div>
        </div>
    </div>
</div>

<div id="globalNews">
    <!-- Pour chaque actualité -->
    <?php foreach ($this->articles as $article): ?>
        <div class="totalBox">
            <div class="box">
                <div class="titreNews">
                    <?= $this->escape($article->titre) ?>
                    <?php if ($this->isAdmin()): ?>
                        <a href="<?= $this->url(array('controller' => 'article', 'action' => 'ecrire', 'id' => $article->id)); ?>">
                            <img class="editArticle" src="/images/edit.png" alt="Modifier" title="Modifier"/>
                        </a>
                        <a href="<?= $this->url(array('controller' => 'article', 'action' => 'supprimer', 'id' => $article->id)); ?>" class="supprimer">
                            <img class="editArticle" src="/images/del.png" alt="Supprimer" title="Supprimer"/>
                        </a>
                    <?php endif; ?>
                </div>
                <div><?php echo $article->contenu ?></div>
                <div style="margin-top:30px">
                    <?php
                    if ($article->author !== null) {
                        $author = 'par '.$article->author->login;
                    } else {
                        $author = '';
                    }
                    ?>
                    <span class="note">Article créé <?= $author ?> le <?php echo $this->escape($article->date->get('dd/MM/YYYY')) ?></span>
                </div>
            </div>
        </div>
    <?php endforeach ?>
    <?= $this->paginator; ?>
</div>

<div id="dialog" style="display: none;"></div>
