<section class="totalBox">
    <div class="box" style="margin-bottom:20px">
        <h1 class="titreNews">Informations légales</h1>
        <p>
            Les informations recueillies sont n&eacute;cessaires pour votre adh&eacute;sion. 
            Elles font l&rsquo;objet d&rsquo;un traitement informatique et sont 
            destin&eacute;es au secr&eacute;tariat de l&rsquo;association.
        </p>
        <p>
            En application des articles 39 et suivants de la loi du 6 janvier 
            1978 modifi&eacute;e, vous b&eacute;n&eacute;ficiez d&rsquo;un droit 
            d&rsquo;acc&egrave;s le de rectification aux informations qui vous concernent.
            Si vous souhaitez exercer ce droit et obtenir communication des informations vous concernant veuillez vous adresser à&nbsp;: 
            <a href="<?= $this->url(array('controller' => 'index', 'action' => 'contact')) ?>">Contact</a>
        </p>
    </div>
</section>
