<section class="totalBox"><div class="box" style="margin-bottom:20px">
	<h1 class="titreNews">Tout ce que vous avez toujours voulu savoir sur les Sesqui sans jamais oser le demander </h1>
<p>Salut à toi nouveau licencié !</p>

<p>
Si tu arrives sur cette page, c'est que tu viens de débarquer chez les Sesquidistus et que tu es à la recherche d'informations sur&nbsp;:
<ul>
	<li>prendre ta licence,</li>
	<li>être tenu au courant de tout ce qui se passe dans le club (tournoi, championnat, soirée, ...),</li>
	<li>comprendre le fonctionnement du club,</li>
	<li>contacter les responsables du club.</li>
</ul>
<p>

<h1>I. Prendre sa licence</h1>

<p>
La première chose à faire est de prendre sa licence. Pour cela, il y a quelques papiers à remplir. Rien de très compliqué, rassure-toi.
<ol>
<li>Remplir la <a href="/files/fiche_adhesion.odt">fiche de renseignement</a> du SUC.</li>
<li>Faire remplir par ton médecin le <a href="/files/certificat_medical.pdf">certificat médical</a>. Ne pas oublier d'y faire figurer le numéro d'ordre du médecin&nbsp;!</li>
<li>Prendre une jolie photo d'identité respectant les contraintes suivantes&nbsp;:<ul>
	<li>Photo en couleur (24 bits)</li>
	<li>Prise de vue de de face</li>
	<li>Prise de vue avec un fond neutre</li>
	<li>Cadrage centré et au plus près du visage</li>
	<li>Format du fichier image : en JPEG ou PNG</li>
	<li>Résolution du fichier image entre 72 et 100 dpi</li>
	<li>Taille de la photo en pixels : 400 (L) x 400 (H) px</li>
</ul></li>
<li>Envoyer tout ça à <a href="mailto:secretaire@frisbee-strasbourg.net">Framb's</a> par e-mail</li>
<li>Payer à <a href="mailto:tresorerie@frisbee-strasbourg.net">Tété ou Titi</a> la licence (loisirs = 52€, Compétition = 77€). Un virement est également possible sur le compte du club (<a href="/files/IBAN_Sesquidistus.pdf">RIB/IBAN</a>).</li>
</ol>
</p>

<p>La licence <em>loisirs</em> permet de participer aux entrainements et à
quelques tournois amicaux auxquels le club participe. La licence
<em>compétition</em> permet, en plus, de participer aux compétitions organisées
par la fédération et aux tournois de préparation à ces compétitions. Il est
important de noter que les joueurs de tous niveaux peuvent prendre une licence
<em>compétition</em>.</p>

<h1>II. Les moyens de communication au sein du club</h1>

Nous avons différents moyens de communication pour différents usages&nbsp;:
<ul>
<li>La mailing-list&nbsp;: Il faut s'y inscrire afin de recevoir par e-mail les informations importantes provenant du Comité Sportif et du Comité Directeur. Pour s'inscrire, envoyer un e-mail à <a href="mailto:sesquidistus-subscribe@yahoogroupes.fr">sesquidistus-subscribe@yahoogroupes.fr</a>.</li>
<li>Le <a href="https://docs.google.com/spreadsheet/ccc?key=0AlgCgnC5berQdEFoQWtnOW1uNWZDRE00VEY1SEk1MlE&usp=drive_web#gid=32" target="_blank">google docs</a> pour s'inscrire aux tournois et aux compétitions. N'hésitez pas à mettre votre prénom dans la colonne des tournois qui vous intéressent&nbsp;!</li>
<li>Le <a href="http://forum.frisbee-strasbourg.net/" target="_blank">forum</a>&nbsp;: élément central de communication. C'est là qu'on prévient de son absence aux entrainements, qu'on organise les départs en tournoi et les remboursements après le tournoi.</li>
<li>Le <a href="http://frisbee-strasbourg.net/calendrier" target="_blank">calendrier</a> sur le site web permet de voir les dates des entrainements, des tournois et des championnats. Il existe également une version au <a href="http://frisbee-strasbourg.net/calendrier/ical" target="_blank">format ICal</a> (ics) pour synchroniser avec tes logiciels de calendrier et tes téléphones.</li>
<li>La page <a href="https://www.facebook.com/pages/Sesquidistus-Strasbourg-France/265227373552209">Facebook du club</a> pour se tenir au courant de l'actualité du club&nbsp;: résultats et impressions suite aux différents tournois et championnats auxquels le club participe</li>
</ul>

<h3>S'inscrire sur le forum</h3>

S'inscrire dans un premier temps sur le <a href="http://www.frisbee-strasbourg.net/user/create" target="_blank">site web</a>. Puis se connecter une première fois au <a href="http://forum.frisbee-strasbourg.net/ucp.php?mode=login" target="_blank">forum</a> avec ses identifiants. Enfin, envoyer un e-mail à <a href="mailto:laurent.leipelt@gmail.com">Lau</a> afin qu'il vous donne les droits d'accès sur le forum.

<h1>III. Les hautes instances du club</h1>

Le club possède deux comités qui ont pour objectif de s'assurer respectivement
du bon déroulement des entrainements et des tournois et de l'administratif.

<h3>Les missions du CS (Comité Sportif)</h3>

Le comité sportif réuni quatre joueurs du club élus au cours de l'assemblée
générale ainsi que le président du club. Ses principaux rôles sont~:

<ul>
	<li>s'assurer de la bonne tenue des entrainements~;</li>
	<li>inscrire des équipes aux compétitions de la FFDF et aux autres tournois~;</li>
	<li>sélectionner les joueurs et les joueuses pour les compétitions de la FFDF en répondant aux objectifs fixés par le comité directeur.</li>
</ul>

<h3>Les missions du CD (Comité Directeur)</h3>

Le comité directeur comprend quatre membres du club élus à l'assemblée générale
dont au moins un président, un trésorier et un secrétaire. Si ses prérogatives
principales concernent l'aspect administratif du club, c'est ce comité qui
définit les objectifs sportifs.

<h1>IV. Les maillots pour les compétitions</h3>

<p>
Pour les joueurs qui souhaitent faire de la compétition, nous souhaitons que
chacun fasse l'achat d'un jeu de maillots complet. Néanmoins, si un joueur n'a
pas eu l'opportunité d'acheter ses maillots pour les premières compétitions, le
club possède quelques jeux de maillots de dépannage. Si le club vous prête un
jeu de maillot, il vous est demandé de le rendre après la
compétition à la personne en charge des maillots du club (<a
href="mailto:webmaster@frisbee-strasbourg.net">Titi</a>).
</p>

<h1>V. Comment prendre contact avec les responsables du club ?</h1>

<p>
Adresse e-mail en cas de galère&nbsp;:
<ul>
	<li>Entraînements&nbsp;: <a href="mailto:comite-sportif@frisbee-strasbourg.net">le comité sportif</a>
	<li>Webmaster&nbsp;: <a href="mailto:webmaster@frisbee-strasbourg.net">Titi</a></li>
	<li>Forum&nbsp;: <a href="mailto:laurent.leipelt@gmail.com">Lau</a></li>
	<li>Mailing list&nbsp;: <a href="mailto:president@frisbee-strasbourg.net">Alban</a></li>
	<li>Le CS&nbsp;: <a href="http://forum.frisbee-strasbourg.net/viewforum.php?f=53" target="_blank">sur le forum</a></li>
	<li>Le CD&nbsp;: <a href="mailto:comite-directeur@frisbee-strasbourg.net">le comité directeur</a></li>
</ul>
</p>
</div></section>
