<section class="totalBox"><div class="box" style="margin-bottom:20px">
	<h1 class="titreNews">Tout ce que vous avez toujours voulu savoir sur les Sesqui sans jamais oser le demander </h1>
<p>Salut à toi nouveau licencié !</p>

<p>
Si tu arrives sur cette page, c'est que tu viens de débarquer chez les Sesquidistus et que tu es à la recherche d'informations sur&nbsp;:
<ul>
	<li>prendre ta licence,</li>
	<li>être tenu au courant de tous ce qui se passe dans le club (tournoi, championnat, soirée, ...),</li>
	<li>comprendre le fonctionnement du club,</li>
	<li>contacter les responsables du club.</li>
</ul>
<p>

<h1>I. Prendre sa licence</h1>

<p>
La première chose à faire est de prendre sa licence. Pour cela, il y a quelques papiers à remplir. Rien de très compliqué, rassure-toi.
<ol>
<li>Remplir la <a href="/files/fiche_adhesion.odt">fiche de renseignement</a> du SUC.</li>
<li>Faire remplir par ton médecin le certificat médical. Ne pas oublié d'y faire figurer le numéro d'ordre du médecin !</li>
<li>Prendre une jolie photo d'identité respectant les contraintes suivantes&nbsp;:<ul>
	<li>Photo en couleur (24 bits)</li>
	<li>Prise de vue de de face</li>
	<li>Prise de vue avec un fond neutre</li>
	<li>Cadrage centré et au plus près du visage</li>
	<li>Format du fichier image : en JPEG ou PNG</li>
	<li>Résolution du fichier image entre 72 et 100 dpi</li>
	<li>Taille de la photo en pixels : 400 (L) x 400 (H) px</li>
</ul></li>
<li>Envoyer tout ça à Framb's par e-mail<?php /*&nbsp;: <a href="mailto:francoise@hoehle.net">francoise@hoehle.net</a>*/?></li>
<li>Payer à Tété ou Titi la licence (loisirs = 52€, Compétition = 77€). Un virement est également possible sur le compte du club (<a href="/files/IBAN_Sesquidistus.pdf">RIB/IBAN</a>).</li>
</ol>
</p>

<!-- Éventuellement mettre un mot ici pour encourager les joueurs à prendre une licence compét'. Du genre : La compét' c'est chouette et même un débutant peut en faire !! -->

<h1>II. Les moyens de communication au sein du club</h1>

Nous avons différents moyens de communication pour différents usages&nbsp;:
<ul>
<li>La mailing-list&nbsp;: Il faut s'y inscrire afin de recevoir par e-mail les informations importantes provenant du Comité Sportif et du Comité Directeur. Pour s'inscrire, envoyer un e-mail à <a href="mailto:sesquidistus-subscribe@yahoogroupes.fr">sesquidistus-subscribe@yahoogroupes.fr</a>.</li>
<li>Le <a href="https://docs.google.com/spreadsheet/ccc?key=0AlgCgnC5berQdEFoQWtnOW1uNWZDRE00VEY1SEk1MlE&usp=drive_web#gid=32" target="_blank">google docs</a> pour s'inscrire aux tournois et aux compétitions. N'hésitez pas à mettre votre prénom dans la colonne des tournois qui vous intéresse&nbsp;!</li>
<li>Le <a href="http://forum.frisbee-strasbourg.net/" target="_blank">forum</a>&nbsp;: Élement central de communication. C'est là qu'on prévient de son absence aux entraînements, qu'on organise les départs en tournoi et les remboursements après le tournoi.</li>
<li>Le <a href="http://frisbee-strasbourg.net/calendrier" target="_blank">calendrier</a> sur le site web permet de voir les dates des entraînements, des tournois et des championnats. Il existe également une version au <a href="http://frisbee-strasbourg.net/calendrier/ical" target="_blank">format ICal</a> (ics) pour synchroniser avec tes logiciels de calendrier et tes téléphones.</li>
</ul>

<h3>S'inscrire sur le forum</h3>

S'inscrire dans un premier temps sur le <a href="http://www.frisbee-strasbourg.net/user/create" target="_blank">site web</a>. Puis se connecter une première fois au <a href="http://forum.frisbee-strasbourg.net/ucp.php?mode=login" target="_blank">forum</a> avec ces identifiants. Enfin, envoyer un e-mail à <?php /*<a href="mailto:laurent.leipelt@gmail.com">*/?>Lau<?php /*</a>*/?> afin qu'il vous donne les droits d'accès sur le forum.

<?php /*
<h1>III. Les hautes instances du club</h1>

Le club possède deux comités qui ont pour objectif de s'assurer respectivement du bon déroulement des entraînements et des tournois et de l'administratif. 

<h3>Qu'est-ce que le CS (Comité Sportif)&nbsp;?</h3>

<h3>Qu'est-ce que le CD (Comité Directeur)&nbsp;?</h3>

<h1>IV. Comment prendre contact avec les responsables du club ?</h1>

<p>
Adresse e-mail en cas de galère&nbsp;:
<ul>
	<li>Entraînement&nbsp;: <a href="mailto:laurent.leipelt@gmail.com">Lau</a>, <a href="mailto:nmerstorf@gmail.com">Niko</a> et <a href="mailto:nmerstorf@gmail.com">PA</a></li>
	<li>Webmaster&nbsp;: <a href="mailto:webmaster@frisbee-strasbourg.net">Titi</a></li>
	<li>Forum&nbsp;: <a href="mailto:laurent.leipelt@gmail.com">Lau</a></li>
	<li>Mailing list&nbsp;: <a href="mailto:alban.foulonneau@uha.fr">Alban</a></li>
	<li>Le CS&nbsp;: <a href="http://forum.frisbee-strasbourg.net/viewforum.php?f=53" target="_blank">sur le forum</a></li>
	<li>Le CD&nbsp;: <a href="mailto:alban.foulonneau@uha.fr">Alban</a></li>
</ul>
</p> */ ?>
</div></section>
