<div id="globalContent">
    <!-- div du menu -->
    <nav>
        <?=
        $this->partial('_sidebar.phtml', array('sections' => $this->sections,
            'controller' => $this->controller,
            'admin' => false,
        	'translate' => $this->translate))
        ?>
    </nav>
    <aside class="totalBox">
        <div id="blocComplementaire" class="box">
            <h3 class="titreNews"><?= $this->translate->_('retrouvez_kym'); ?></h3>
            <a href="http://ffindr.com/fr/event/france/keep-your-mustache-14" alt="FFindr.com" target="_blank">
                <img alt="Sur FFindr" src="/images/social/ffindr-flags.png" title="Sur FFindr" />
            </a>
            <a href="https://www.facebook.com/pages/Sesquidistus-Strasbourg-France/265227373552209" alt="Facebook.com" target="_blank">
                <img src="/images/social/facebook-logo.jpg" alt="Sur Facebook" title="Sur Facebook" />
            </a>
        </div>
    </aside>
    <!-- div du contenu de la page -->
    <section id="news" class="box">
        <h1 class="titreNews"><?= $this->translate->_('diapo_google'); ?></h1>
        <div class="contenuNews">
            <div>
                <?= $this->translate->_('diapo_google_texte'); ?>
                <form action="<?= $this->url(array('controller' => 'kym', 'action' => 'diaporama')); ?>" method="POST">
                    <input type="text" id="url" name="url" style="width: 500px" /><br/>
                    <label for="height"><?= $this->translate->_('hauteur'); ?></label><input type="number" id="height" name="height" value="368" /><br/>
                    <label for="width"><?= $this->translate->_('largeur'); ?></label><input type="number" id="width" name="width" value="550" /><br/>
                    <input type="submit" value="Valider" class="bouton1" />
                </form>
                <?php if (!is_null($this->embeddedCode)): ?>
                <textarea style="width: 100%; height: 150px;" readonly><?= $this->embeddedCode ?></textarea>
                <?php endif; ?>
            </div>
        </div>
    </section>
</div>