  <?php /*
  <?php if (!empty($this->album)): ?>
  <aside id="galerie" class="totalBox">
  <div class="box" style="min-height:150px;">
  <h2 class="titreNews">Photos & vidéos</h2>
  <div style="position:relative;">
  <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'index', 'kym' => true)) ?>">
  <img style="width:170px;" src="<?= $this->album->getFirstImage()->getNomWithMiniPath() ?>" alt="Photos & vidéos du KYM" title="Photos & vidéos du KYM" />
  </a>
  </div>
  </div>
  </aside>
  <?php endif; ?>
  </div>
 * 
 */ ?>
<div id="globalContent">
    <!-- div du menu -->
    <nav>
        <?=
        $this->partial('_sidebar.phtml', array('sections' => $this->sections,
            'id' => $this->kym->id,
            'controller' => $this->controller,
            'admin' => false))
        ?>
    </nav>
    <aside class="totalBox">
        <div id="blocComplementaire" class="box">
            <h3 class="titreNews">Retrouvez le KYM</h3>
            <a href="http://ffindr.com/fr/event/keep-your-mustache-13" alt="FFindr.com">
                <img alt="Sur FFindr" src="/images/social/ffindr-flags.png" title="Sur FFindr" />
            </a>
            <a href="https://www.facebook.com/pages/Sesquidistus-Strasbourg-France/265227373552209" alt="Facebook.com">
                <img src="/images/social/facebook-logo.jpg" alt="Sur Facebook" title="Sur Facebook" />
            </a>
        </div>
    </aside>
    <!-- div du contenu de la page -->
    <?php 
    $class = '';
    if ($this->kym->id != 1){
        $class = 'box';
    } ?>
    <section id="news" class="<?= $class ?>">
        <?php if ($this->kym->id == 1): //Section Nouvelles ?>
            <?php if (count($this->articles) > 0): ?>
                <?php foreach ($this->articles as $article): ?>
                    <?= $this->partial('article/_article.phtml', array('article' => $article)); ?>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="totalBox">
                    <div class="box">
                        <h2 class="titreNews">Aucun article à propos du KYM...</h2>
                        <div style="text-align: justify;">
                            Aucun article à propos du Keep Your Moustache pour le moment. 
                            Mais il y en aura probablement bientôt des nouveaux.
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <h1 class="titreNews"><?= $this->escape($this->kym->titre); ?></h1>
            <div class="contenuNews">
                <div><?= $this->kym->contenu ?></div>
                <?php if ($this->isAdmin()): ?>
                    <form method="POST" id="frmContent" action="<?= $this->url(array('controller' => 'kym', 'action' => 'modifier')); ?>">
                        <textarea id="content" name="content"><?= $this->kym->contenu ?></textarea>
                        <input type="hidden" id="title" name="title"/>
                        <input type="submit" value="Valider le contenu" class="bouton1" />
                    </form>
                <?php endif; ?>
            </div>
            <?php if ($this->kym->id == 2): // Infos pratiques ?>
                <?= $this->partial('lieu/_affiche.phtml', array('lieux' => $this->lieu)); ?>
                <?php if ($this->isAdmin()){
                    echo $this->partial('lieu/_action.phtml', array('lieux' => $this->lieu));
                } ?>
            <?php endif; ?>
        <?php endif; ?>
        <?= $this->paginator; ?>
    </section>
    <?php if ($this->kym->id != 1 && $this->isAdmin()): ?>
        <div id="modifContent">
            <input class="bouton1" type="button" value="Modifier le contenu" />
        </div>
    <?php endif; ?>
</div>
