<section class="totalBox">
    <div class="box" style="margin-bottom:20px">
        <h1 class="titreNews"><?php echo $this->translate->_('a_propos'); ?></h1>
        <p><?php echo $this->translate->_('en_construction'); ?></p>
        <hr style="margin-top:100px;"/>
            <div>
            	<?php echo $this->translate->_('site_universitaire'); ?>:
                <table style="margin-left:30px; margin-top:30px;">
                    <tr>
                        <td>
                            <img src="/images/favicon.ico" style="width:10px;height:10px" alt="Logo" /> Benoît SOUFFLET&nbsp;:
                        </td>
                        <td><a href="mailto:benoit.soufflet@gmail.com">benoit.soufflet@gmail.com</a></td>
                    </tr>
                    <tr>
                        <td>
                            <img src="/images/favicon.ico" style="width:10px;height:10px" alt="Logo" /> Pierre LEROY&nbsp;:
                        </td>
                        <td><a href="mailto:pleroy@etu.unistra.fr">pleroy@etu.unistra.fr</a></td>
                    </tr>
                    <tr>
                        <td>
                            <img src="/images/favicon.ico" style="width:10px;height:10px" alt="Logo" /> Steve DURRHEIMER&nbsp;:
                        </td>
                        <td><a href="mailto:durrheimer@etu.unistra.fr">durrheimer@etu.unistra.fr</a></td>
                    </tr>
                </table>
            </div>
    </div>
</section>
