<?php $contact = $this->contact ?>
<section class="totalBox"> 
    <?php if ($this->modifier): ?>
        <form id="frmContact" method="POST" action="<?= $this->url(array('controller' => 'index', 'action' => 'contact', 'modifier' => true)) ?>">
        <?php endif; ?>
            <div class="box" style="margin-bottom:20px" itemscope itemtype="http://schema.org/Person">
            <h1 class="titreNews">
                <?php echo $this->translate->_('comment_contacter') ?>?
                <?php if ($this->isAdmin() && !$this->modifier): ?>
                    <a href="<?= $this->url(array('controller' => 'index', 'action' => 'contact', 'modifier' => true)); ?>">
                        <img class="editContact" src="/images/edit.png" alt="Editer"/>
                    </a>
                <?php endif; ?>
            </h1>
            <p>
                <?php if ($this->modifier): ?>
                    Prénom&nbsp;: <input type="text" value="<?= $contact->prenom ?>" class="required" maxlength="50" id="firstName" name="firstName" /><br/>
                    Nom&nbsp;: <input type="text" value="<?= $contact->nom ?>" class="" maxlength="50" id="lastName" name="lastName" />
                <?php else: ?>
                    <strong itemprop="name"><?= $contact->prenom ?> <?= $contact->nom ?></strong>
                <?php endif; ?>
            </p>
            <p>
                <span style="color: #0000ff;">
                    <?php if ($this->modifier): ?>
                        E-mail&nbsp;: <input type="email" value="<?= $contact->email ?>" class="required email" maxlength="100" id="email" name="email" />
                    <?php else: ?>
                        <strong itemprop="email"><?= $contact->email ?></strong>
                    <?php endif; ?>
                </span>
            </p>
            <?php $tel = $contact->telephone; ?>
            <?php if ($this->modifier): ?>
                Tél.&nbsp;: <input type="tel" value="<?= $contact->telephone ?>" class="" maxlength="20" id="phone" name="phone" />
            <?php else: ?>
                <?php if (!empty($tel)): ?>
                <p>Tél&nbsp;: <span itemprop="telephone"><?= $contact->telephone ?></span></p>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <?php if ($this->modifier): ?>
            <input type="submit" value="Valider le contenu" class="bouton1" style="float: right;" />
        </form>
    <?php endif; ?>
</section>
