<div class="totalBox">
    <div class="box">
        <h1 class="titreNews"><?php echo $this->translate->_('connexion'); ?>:</h1>
        <p><?php echo $this->translate->_('connexion_remplir_formulaire'); ?>:</p>
        <?php $this->loginForm->setAction($this->url()); ?>
        <form id="selection" action="<?= $this->loginForm->getAction(); ?>" method="<?= $this->loginForm->getMethod(); ?>">
            <?php if (count($this->loginForm->getErrorMessages()) > 0): ?>
            <div class="error">
            <?php foreach ($this->loginForm->getErrorMessages() as $error): ?>
            <?= $error ?>
            <?php endforeach; ?>
            </div>
            <?php endif;?>
            <div class="log">
                <span class="lbl_log"><?= $this->loginForm->login->renderLabel(); ?></span>
                <span class="in_log"><?= $this->loginForm->login->renderViewHelper(); ?></span>
            </div>
            <div class="log">
                <span class="lbl_log"><?= $this->loginForm->passwd->renderLabel(); ?></span>
                <span class="in_log"><?= $this->loginForm->passwd->renderViewHelper(); ?></span>
            </div>
            <div class="sub_log">
                <?= $this->loginForm->submit->renderViewHelper(); ?>
                <?= $this->loginForm->reset->renderViewHelper(); ?>
            </div>
        </form>
        <div class="log">
            <?php 
                // TODO page forget password 
            ?>
            <p>[ <a href="<?= $this->url(array('controller' => 'auth', 'action' => 'forget')); ?>"><?php echo $this->translate->_('mdp_oublie'); ?></a> ]</p>
        </div>
        <div class="log" style="text-align: center;">
       		<a id="login_persona" href="#" class="persona-button dark"><span><?php echo $this->translate->_('connecter_persona'); ?></span></a>
        </div>
    </div>
</div>

