<?php if ($this->pageCount > 1): ?>
    <div class="pagination">

        <?php if (isset($this->previous)): ?>
            <!-- First page link -->
            <a href="<?php echo $this->url(array('page' => $this->first)); ?>" title="Première page">
                ◄◄
            </a>
            <!-- Previous page link -->
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" title="Précédent">
                ◄
            </a>
        <?php else: ?>
            <span class="disabled">◄◄</span>
            <span class="disabled">◄</span>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>">
                    <?php echo $page; ?>
                </a>
            <?php else: ?>
                <span class="current"><?php echo $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>


        <?php if (isset($this->next)): ?>
            <!-- Next page link -->
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>" title="suivant">
                ►
            </a>
            <!-- Last page link -->
            <a href="<?php echo $this->url(array('page' => $this->last)); ?>" title="Dernière page">
                ►►
            </a>
        <?php else: ?>
            <span class="disabled">►</span>
            <span class="disabled">►►</span>
        <?php endif; ?>
    </div>
<?php endif; ?>