<script type="text/javascript">
    $(document).ready(function() {
        $("#menuDrop").dropmenu();
        $("#menuDrop").fadeTo(0,1);
        $('#menuDrop li:nth-child(<?php echo $this->current ?>)').children().addClass('selected');
    });
</script>
<div id="barreMenu">
    <ul id="menuDrop" class="apple">
        <li><a href="<?php echo $this->url(array('controller'=>'index')) ?>">Accueil</a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'calendrier')) ?>">Calendrier</a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'club')) ?>">Le club</a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'ultimate')) ?>">Ultimate Frisbee</a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'galerie')) ?>">Galeries</a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'evenement')) ?>">Nos évènements</a></li>
        <li><a href="">KYM '12</a></li>
        <li><a href="<?php echo $this->url(array('controller'=>'contact')) ?>">Contact</a></li>
    </ul>
</div>

