<div id="Menu" class="box">
    <div class="titreNews">Sections</div>
    <?php foreach ($this->sections as $section): ?>
        <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'index', 'id' => $section->id)) ?>">
            <?php $class = ($section->id == $this->id) ? 'bouton6' : 'bouton2' ?>
            <div class="<?= $class ?> bouton">
                <span><?= $this->escape($section->titre) ?></span>
            </div>
        </a>
    <?php endforeach; ?>
    <?php if ($this->admin): ?>
        <span class="bouton1 actionContent" style="" id="ajoutCat" title="Ajouter une catégorie">+</span>
        <span class="bouton1 actionContent" style="" id="supprCat" title="Supprimer une catégorie">-</span>
        <a class="doc" href="./doc/doc_club_ultimate/doc_admin_club_ultimate.html" target="_blank">
            <img src="./images/help.png" title="aide en ligne" alt="aide"/>
        </a>
    <?php endif; ?>
</div>

