<div id="Menu" class="box">
    <div class="titreNews">Sections</div>
    <?php foreach ($this->sections as $section): ?>
        <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'index', 'id' => $section->id)) ?>">
            <?php $class = ($section->id == $this->id) ? 'bouton6' : 'bouton2' ?>
            <div class="<?= $class ?> bouton">
                <span><?= $this->escape($section->titre) ?></span>
            </div>
        </a>
    <?php endforeach; ?>
</div>

