<?php foreach ($this->everybody as $key => $members) : ?>
    <?= $key; ?><hr/>
    <table itemscope itemtype="http://schema.org/Person">
        <?php $i = 0; ?>
        <?php foreach ($members as $member): ?>
            <?php if ($i % $this->nbPerLine == 0): ?>
                <?php if ($i != 0): ?>
                </tr>
            <?php endif; ?>
            <tr>
            <?php endif; ?>
            <td>
                <div class="bouton4">
                    <a class="black" href="<?= $this->url(array('controller' => 'user', 'action' => 'view', 'id' => $member->id_membre)); ?>">
                        <img src="<?= $member->avatarPath; ?>" itemprop="image"
                             title="<?= $this->escape($member->prenom); ?>" alt="<?= $this->escape($member->prenom); ?>" />
                        <span itemprop="name"><?= $this->escape($member->prenom); ?></span>
                    </a>
                </div>
            </td>
            <?php $i++; ?>
        <?php endforeach; ?>
    </table>
<?php endforeach; ?>