<?php if (!empty($this->lieux)) foreach ($this->lieux as $lieu): ?>
    <div class="box map" id="map<?= $lieu->id; ?>" itemscope itemtype="http://schema.org/Place">
        <h2 class="titreNews"><?= $this->escape($lieu->nom); ?></h2>
        <div id="map_canvas<?= $lieu->id; ?>" class="canvas" itemprop="map"></div>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#map_canvas<?= $lieu->id; ?>').gmap3({
                    marker: {
                    	address: "<?= $this->escape($lieu->adresse); ?>",                        
                    },
                    map: {
                        options: {
	                        zoom: 14
                        },
                    }
                });
            });
        </script>
        <p itemprop="address"><?= $this->escape($lieu->adresse); ?></p>
    </div>
<?php endforeach; ?>