<div id="menuSelectionCat">
    <a id="consultButton" class="bouton1 <?= ($this->action == 'index')?'boutonPageCourante':''; ?>" href="<?= $this->url(array('controller' => 'calendrier', 'action' => 'index')); ?>">Consulter le calendrier</a>
    <a id="ajoutButton" class="bouton1 <?= ($this->action == 'editer')?'boutonPageCourante':''; ?>" href="<?= $this->url(array('controller' => 'calendrier', 'action' => 'editer')); ?>">Ajouter un évènement</a>
</div>