<?= $this->partial('calendrier/_menuAdmin.phtml', array('action' => 'ajouter')); ?>

<div class="totalBox">
    <div  class="box" style="background-color:#EEE">
        <div class="titreNews">Ajout d'un évènement</div>
        <form id="formAjout" style="display:inline" method="POST" action="<?= $this->url(array('controller' => 'calendrier', 'action' => 'ajouter')); ?>">
            <div id="globCalendar">
                <div style="text-align:left">
                    <div style="float:right">
                        <a href="./doc/doc_event/doc_admin_event.html#ajouter_evenement">
                            <img src="/images/help.png" alt="help" title="aide en ligne" />
                        </a>
                    </div>
                    <?php
                    /*
                     * Liste des types d'évènement
                     */
                    ?>
                    <div id="listeType" class="bouton2 dataForm">
                        <span id="spanListeType" style="font-size:12px; padding:0 8px 0 3px">Type</span>
                        <div id="divListeEvent" style="display:inline">
                            <select id="listeEvent" style="font-size:12px" name="typeEvent">
                                <?php foreach ($this->types as $type): ?>
                                    <option value="<?= $type->numero ?>"><?= $type->nom; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div><?php /*
                                  <div id="divButtonType" style="position:absolute; margin-top:-30px; margin-left:265px">
                                  <span id="modifType" title="Modifier ce type d'évènement" class="bouton1">#</span>
                                  <span id="supprType" title="Supprimer ce type d'évènement" class="bouton1">X</span>
                                  <span id="addType" title="Ajouter un type d'évènement à la base de données" class="bouton1">+</span>
                                  </div> */ ?>

                    <?php
                    /*
                     * Nom de l'évènement
                     */
                    ?>
                    <div class="bouton2 dataForm">
                        <span style="font-size:12px;  padding:0 10px 0 3px">Nom</span>
                        <input class="inputStyle required" id="textevenement" name="nomEvent" maxlength="35" type="text"/>
                    </div>

                    <?php
                    /*
                     * Liste des lieux d'évènements
                     */
                    ?>
                    <div id="listeLieu" class="bouton2 dataForm">
                        <span id="spanListeLieu" style="font-size:12px; padding:0 11px 0 3px">Lieu</span>
                        <div id="divListeLieu" style="display:inline">
                            <select id="id_lieuEvent" style="font-size:12px" name="id_lieuEvent">
                                <?php foreach ($this->lieux as $lieu): ?>
                                    <option value="<?= $lieu->id ?>"><?= $lieu->nom; ?></option>
                                <?php endforeach; ?>
                                <option value="0" selected="selected">Autre...</option>
                            </select>
                        </div>
                        <input id="text_lieuEvent" class="inputStyle" style="margin-left:50px" type="text" maxlength="35" name="text_lieuEvent" />
                    </div>

                    <?php
                    /*
                     * Durée et dates de l'évènement
                     */
                    ?>
                    <div class="bouton2 dataForm2">
                        <span style="font-size:12px;  padding:0 0 0 3px">Durée (jour)</span>
                        <div style="display:inline">
                            <select style="font-size:12px" id="duree_event" name="duree_event">
                                <?php for ($i = 1; $i <= 7; $i++): ?>
                                    <option value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                    </div>

                    <div class="bouton2 dataForm2">
                        <span style="font-size:12px;  padding:0 0 0 3px">Début</span>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireDebutHeure" name="debutEventHeure">
                                <?php for ($i = 0; $i < 24; $i++): ?>
                                    <option value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireDebutMinute" name="debutEventMinute">
                                <?php for ($i = 0; $i < 60; $i = $i + 5): ?>
                                    <option value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                        <input type="checkbox" id="checkHoraire" name="boolHoraire" value="true" checked="checked" title="Ne pas définir d'horaire" />
                    </div>
                    <div class="bouton2 dataForm2">
                        <span style="font-size:12px; padding:0 19px 0 3px">Fin</span>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireFinHeure" name="finEventHeure">
                                <?php for ($i = 0; $i < 24; $i++): ?>
                                    <option value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireFinMinute" name="finEventMinute">
                                <?php for ($i = 0; $i < 60; $i = $i + 5): ?>
                                    <option value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                    </div>
                </div>

                <?php
                /*
                 * Choix de la date
                 */
                ?>
                <div style="text-align:left; margin:20px 0px 30px 0px">
                    <div style="font-size:12px; font-weight:bold; margin-left:4px">
                        Sélectionnez la date de début de l'évènement à ajouter&nbsp;: <br />
                        <span style="font-style:italic; font-size:11px; font-weight:normal">
                            (Vous pouvez sélectionner plusieurs dates afin d'enregistrer plusieurs fois le même évènement à des dates différentes)
                        </span>
                    </div>
                </div>
                <?php /*
                  <div style="text-align:center">
                  <span style="font-size:10px" id="prevDate" class="bouton1">&lt;&lt; Mois précédents</span>
                  <span style="margin-left:70px; font-size:10px" id="nextDate" class="bouton1">Mois suivants &gt;&gt;</span>
                  </div> */ ?>
                <div id="datepicker">
                    <span id="errorDatepicker" class="error" style="display:none">Sélectionner au moins une date</span>
                    <?php
                    $displayedMonth = new Zend_Date();
                    $displayedMonth->setDay(1);
                    ?>
                    <?php for ($month = 0; $month < 3; $month++): ?>
                        <div class="calendar" style="left:<?= 40 + $month * 230 ?>px">
                            <table>
                                <thead>
                                    <tr class="calendar">
                                        <?php
                                        $jours = array('Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa', 'Di');
                                        $nbJours = count($jours);
                                        for ($i = 0; $i < $nbJours; $i++):
                                            if ($i >= $nbJours - 2) {
                                                $color = 'color:#d72c2c;';
                                            } else {
                                                $color = '';
                                            }
                                            ?>
                                            <td style="text-align:center; font-weight:bold; <?= $color ?>"><?= $jours[$i] ?></td>
                                        <?php endfor; ?>
                                    </tr>
                                </thead>
                                <?php $nbJoursMois = $displayedMonth->get(Zend_Date::MONTH_DAYS); ?>
                                <tbody>
                                    <?php
                                    $jourCourant = new Zend_Date($displayedMonth);
                                    for ($i = 0; $i < $nbJoursMois; $i++):
                                        // Si jourCourant est lundi
                                        if ($jourCourant->get(Zend_Date::WEEKDAY_DIGIT) == 1):
                                            ?>
                                            <tr>
                                                <?php
                                            endif;
                                            // Création des cases vides de début de mois 
                                            if ($i == 0):
                                                ?>
                                            <tr>
                                                <?php
                                                $dayOfWeeks = ($jourCourant->get(Zend_Date::WEEKDAY_DIGIT) + $nbJours - 1) % $nbJours;
                                                for ($j = 0; $j < $dayOfWeeks; $j++):
                                                    ?>
                                                    <td class="calendarVide">&nbsp;</td>
                                                    <?php
                                                endfor;
                                            endif
                                            ?>
                                            <td 
                                                title="<?= $jourCourant->get(Zend_Date::DAY.'/'.Zend_Date::MONTH_SHORT.'/'.Zend_Date::YEAR); ?>"
                                                class="calendar defaultCalendar">
                                                <div class="day">
                                                    <?= $jourCourant->get(Zend_Date::DAY) ?>
                                                </div>
                                            </td><?php
                                            // Création des cases vides de fin de mois 
                                            if ($i == $nbJoursMois - 1):
                                                $dayOfWeeks = $jourCourant->get(Zend_Date::WEEKDAY_DIGIT);
                                                if ($dayOfWeeks != 0):
                                                    for ($j = 0; $j < $nbJours - $dayOfWeeks; $j++):
                                                                ?>
                                                        <td class="calendarVide">&nbsp;</td>
                                                        <?php
                                                    endfor;
                                                endif;
                                                ?>

                                            </tr>
                                            <?php
                                        endif;
                                        // Si jourCourant est dimanche
                                        if (ucwords($jourCourant->get(Zend_Date::WEEKDAY)) == $jours[$nbJours - 1]):
                                            ?>
                                            </tr>
                                        <?php endif; ?>

                                        <?php
                                        $jourCourant->addDay(1);
                                    endfor;
                                    ?>
                                </tbody>
                            </table>
                            <span class="spanEcrireDate"><?= $displayedMonth->get(Zend_Date::MONTH_NAME.' '.Zend_Date::YEAR); ?></span>
                        </div>
                        <?php $displayedMonth->addMonth(1); ?>
                    <?php endfor; ?>
                </div>
                <input type="hidden" id="hdnDates" name="hdnDates" class="required" />
                <?php
                /*
                 * Commentaire
                 */
                ?>
                <div id="commentaireEvenement">
                    <div style="margin-left:0px; width:300px">
                        <div class="totalBox">
                            <div class="box">
                                <div class="titreNews">Commentaire (facultatif)</div>
                                <textarea style="font-size:12px;" id="CommentaireEvent" name="commentaireEvent" tabindex="4" cols="35" rows="8"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div style="text-align:right">
                    <input type="reset" id="resetDate" class="bouton1" value="Remise à zéro" />
                    <input type="submit" id="validerDate" class="bouton1" style="padding:8px 5px; font-size:14px" value="Valider l'évènement" />
                </div>
            </div>
        </form>
    </div>
</div>

<?php /*
  <!-- Formulaire action Type -->
  <div id="divFormActionType" style="display:none">
  <div style="float:right">
  <a href="./doc/doc_event/doc_admin_type_event.html">
  <img src="/images/help.png" alt="help" title="aide en ligne" />
  </a>
  </div>
  <form id="formActionType" method="post" action="./modules/calendrier/action_type.php">
  <div id="titreNewType" class="bouton2 dataForm">
  <span style="font-size:12px;  padding:0 10px 0 3px">Titre:</span>
  <input id="type_nom" class="inputStyle" type="text" name="nomType" />
  </div>
  <div class="bouton2 dataForm">
  <span style="font-size:12px;  padding:0 10px 0 3px">Couleur:</span>
  <input id="type_color" style="width:100px; font-size:12px" type="text" name="color" />
  <span id="Button_type_color" class="bouton1">Choix</span>
  </div>
  <input id="idType_event" type="hidden" name="idType_event" />
  <input id="modeType" type="hidden" name="modeType" />
  </form>
  </div>
  <!-- Fin formulaire ajout Type -->

  <!-- Formulaire ajout Type -->
  <form style="display:none" id="formSupprType" method="post" action="./modules/calendrier/suppr_type.php">
  <input id="idType_eventSuppr" type="hidden" name="idType_eventSuppr" />
  </form>
  <!-- fin Formulaire ajout Type -->
 */ ?>