<?php if ($this->evenement->id === null): ?>
    <?= $this->partial('calendrier/_menuAdmin.phtml', array('action' => 'editer')); ?>
<?php endif; ?>

<div class="totalBox">
    <div  class="box" style="background-color:#EEE">
        <h1 class="titreNews">
            <?php if ($this->evenement->id === null): ?>
                Ajout  
            <?php else: ?>
                Modification 
            <?php endif; ?>
            d'un évènement
        </h1>
        <form id="formAjout" style="display:inline" method="POST" action="<?= $this->url(array('controller' => 'calendrier', 'action' => 'editer')); ?>">
            <input type="hidden" id="hdnId" name="hdnId" value="<?= $this->evenement->getId(); ?>"/>
            <div id="globCalendar">
                <div style="text-align:left">
                    <div style="float:right">
                        <a href="./doc/doc_event/doc_admin_event.html#ajouter_evenement">
                            <img src="/images/help.png" alt="help" title="aide en ligne" />
                        </a>
                    </div>
                    <?php
                    /*
                     * Liste des types d'évènement
                     */
                    ?>
                    <div id="listeType" class="bouton2 dataForm">
                        <span id="spanListeType" style="font-size:12px; padding:0 8px 0 3px">Type</span>
                        <div id="divListeEvent" style="display:inline">
                            <select id="listeEvent" style="font-size:12px" name="typeEvent">
                                <?php foreach ($this->types as $type): ?>
                                    <?php
                                    $selected = "";
                                    if ($this->evenement->getType() == $type->id) {
                                        $selected = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?= $selected; ?> value="<?= $type->id ?>"><?= $type->nom; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div id="divButtonType" style="position:absolute; margin-top:-30px; margin-left:265px">
                        <?php //<a href="#" id="modifType" title="Modifier ce type d'évènement" class="bouton1">#</a> ?>
                        <a href="<?= $this->url(array('controller' => 'type-event', 'action' => 'supprimer')); ?>" 
                           id="supprType" title="Supprimer ce type d'évènement" class="bouton1">X</a>
                        <a href="#" id="addType" title="Ajouter un type d'évènement" class="bouton1">+</a>
                    </div> 

                    <?php
                    /*
                     * Nom de l'évènement
                     */
                    ?>
                    <div class="bouton2 dataForm">
                        <span style="font-size:12px;  padding:0 10px 0 3px">Nom</span>
                        <input class="inputStyle required" id="textevenement" name="nomEvent" maxlength="35" type="text" value="<?= $this->evenement->getTitre(); ?>" />
                    </div>

                    <?php
                    /*
                     * Liste des lieux d'évènements
                     */
                    ?>
                    <div id="listeLieu" class="bouton2 dataForm">
                        <span id="spanListeLieu" style="font-size:12px; padding:0 11px 0 3px">Lieu</span>
                        <div id="divListeLieu" style="display:inline">
                            <?php $id_lieu = $this->evenement->getId_lieu(); ?>
                            <select id="id_lieuEvent" style="font-size:12px" name="id_lieuEvent">
                                <?php foreach ($this->lieux as $lieu): ?>
                                    <?php
                                    $selected = "";
                                    if ($id_lieu == $lieu->id) {
                                        $selected = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?= $selected; ?> value="<?= $lieu->id ?>"><?= $lieu->nom; ?></option>
                                <?php endforeach; ?>
                                <?php
                                $selected = "";
                                if (empty($id_lieu)) {
                                    $selected = 'selected="selected"';
                                }
                                ?>
                                <option value="0" <?= $selected; ?>>Autre...</option>
                            </select>
                        </div>
                        <input id="text_lieuEvent" class="inputStyle" style="margin-left:50px" type="text" maxlength="35" name="text_lieuEvent" value="<?= $this->evenement->getLieu(); ?>" />
                    </div>

                    <?php
                    /*
                     * Durée et dates de l'évènement
                     */
                    ?>
                    <div class="bouton2 dataForm2">
                        <span style="font-size:12px;  padding:0 0 0 3px">Durée (jour)</span>
                        <div style="display:inline">
                            <select style="font-size:12px" id="duree_event" name="duree_event">
                                <?php for ($i = 1; $i <= 7; $i++): ?>
                                    <?php
                                    $selected = "";
                                    if ($this->evenement->getDuree() == $i) {
                                        $selected = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?= $selected ?> value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                    </div>

                    <?php
                    $heureDebut = 0;
                    $minuteDebut = 0;
                    $heureFin = 0;
                    $minuteFin = 0;
                    $horaire_debut = $this->evenement->getHoraire_debut();
                    $horaire_fin = $this->evenement->getHoraire_fin();
                    if (!empty($horaire_debut)) {
                        list($heureDebut, $minuteDebut) = explode('h', $horaire_debut);
                    }
                    if (!empty($horaire_fin)) {
                        list($heureFin, $minuteFin) = explode('h', $horaire_fin);
                    }
                    ?>
                    <div class="bouton2 dataForm2">
                        <span style="font-size:12px;  padding:0 0 0 3px">Début</span>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireDebutHeure" name="debutEventHeure">
                                <?php for ($i = 0; $i < 24; $i++): ?>
                                    <?php
                                    $selected = "";
                                    if ($heureDebut == $i) {
                                        $selected = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?= $selected; ?> value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireDebutMinute" name="debutEventMinute">
                                <?php for ($i = 0; $i < 60; $i = $i + 5): ?>
                                    <?php
                                    $selected = "";
                                    if ($minuteDebut == $i) {
                                        $selected = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?= $selected; ?> value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                        <?php
                        $checked = "";
                        if ($heureDebut == 0 && $minuteDebut == 0 && $heureFin == 0 && $minuteFin == 0) {
                            $checked = 'checked="checked"';
                        }
                        ?>
                        <input type="checkbox" id="checkHoraire" name="boolHoraire" value="true" 
                               <?= $checked ?> title="Ne pas définir d'horaire" />
                    </div>
                    <div class="bouton2 dataForm2">
                        <span style="font-size:12px; padding:0 19px 0 3px">Fin</span>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireFinHeure" name="finEventHeure">
                                <?php for ($i = 0; $i < 24; $i++): ?>
                                    <?php
                                    $selected = "";
                                    if ($heureFin == $i) {
                                        $selected = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?= $selected; ?> value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                        <div style="display:inline">
                            <select style="font-size:12px" class="horaire" id="horaireFinMinute" name="finEventMinute">
                                <?php for ($i = 0; $i < 60; $i = $i + 5): ?>
                                    <?php
                                    $selected = "";
                                    if ($minuteFin == $i) {
                                        $selected = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?= $selected; ?> value="<?= $i; ?>"><?= $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                    </div>
                </div>

                <?php
                /*
                 * Choix de la date
                 */
                ?>
                <div style="text-align:left; margin:20px 0px 30px 0px">
                    <div style="font-size:12px; font-weight:bold; margin-left:4px">
                        <p>Sélectionnez la date de début de l'évènement à ajouter&nbsp;:</p>
                        <input type="radio" id="rdManuel" name="rdDate[]" /><label for="rdManuel">Sélection manuel</label><br />
                        <input type="radio" id="rdCalendar" name="rdDate[]" checked="checked" /><label for="rdCalendar">Sélection calendrier</label>
                    </div>
                </div>
                <div id="calendarDatepicker">
                    <p style="font-style:italic; font-size:11px; font-weight:normal">
                            (Vous pouvez sélectionner plusieurs dates afin d'enregistrer plusieurs fois le même évènement à des dates différentes)
                    </p>
                    <div id="datepicker">
                    <span id="errorDatepicker" class="error" style="display:none">Sélectionner au moins une date</span>
                    <?php
                    $displayedMonth = new Zend_Date();
                    $displayedMonth->setDay(1);
                    ?>
                    <?php for ($month = 0; $month < 3; $month++): ?>
                        <div class="calendar" style="left:<?= 40 + $month * 230 ?>px">
                            <table>
                                <thead>
                                    <tr class="calendar">
                                        <?php
                                        $jours = array('Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa', 'Di');
                                        $nbJours = count($jours);
                                        for ($i = 0; $i < $nbJours; $i++):
                                            if ($i >= $nbJours - 2) {
                                                $color = 'color:#d72c2c;';
                                            } else {
                                                $color = '';
                                            }
                                            ?>
                                            <td style="text-align:center; font-weight:bold; <?= $color ?>"><?= $jours[$i] ?></td>
                                        <?php endfor; ?>
                                    </tr>
                                </thead>
                                <?php $nbJoursMois = $displayedMonth->get(Zend_Date::MONTH_DAYS); ?>
                                <tbody>
                                    <?php
                                    $jourCourant = new Zend_Date($displayedMonth);
                                    for ($i = 0; $i < $nbJoursMois; $i++):
                                        // Si jourCourant est lundi
                                        if ($jourCourant->get(Zend_Date::WEEKDAY_DIGIT) == 1):
                                            ?>
                                            <tr>
                                                <?php
                                            endif;
                                            // Création des cases vides de début de mois 
                                            if ($i == 0):
                                                ?>
                                            <tr>
                                                <?php
                                                $dayOfWeeks = ($jourCourant->get(Zend_Date::WEEKDAY_DIGIT) + $nbJours - 1) % $nbJours;
                                                for ($j = 0; $j < $dayOfWeeks; $j++):
                                                    ?>
                                                    <td class="calendarVide">&nbsp;</td>
                                                    <?php
                                                endfor;
                                            endif
                                            ?>
                                            <td 
                                                title="<?= $jourCourant->get(Zend_Date::DAY.'/'.Zend_Date::MONTH_SHORT.'/'.Zend_Date::YEAR); ?>"
                                                class="calendar defaultCalendar <?= (!is_null($this->evenement->getDate()) && $jourCourant->compareDate($this->evenement->getDate()) === 0) ? 'selected' : ''; ?>">
                                                <div class="day">
                                                    <?= $jourCourant->get(Zend_Date::DAY) ?>
                                                </div>
                                            </td><?php
                                            // Création des cases vides de fin de mois 
                                            if ($i == $nbJoursMois - 1):
                                                $dayOfWeeks = $jourCourant->get(Zend_Date::WEEKDAY_DIGIT);
                                                if ($dayOfWeeks != 0):
                                                    for ($j = 0; $j < $nbJours - $dayOfWeeks; $j++):
                                                                ?>
                                                        <td class="calendarVide">&nbsp;</td>
                                                        <?php
                                                    endfor;
                                                endif;
                                                ?>

                                            </tr>
                                            <?php
                                        endif;
                                        // Si jourCourant est dimanche
                                        if (ucwords($jourCourant->get(Zend_Date::WEEKDAY)) == $jours[$nbJours - 1]):
                                            ?>
                                            </tr>
                                        <?php endif; ?>

                                        <?php
                                        $jourCourant->addDay(1);
                                    endfor;
                                    ?>
                                </tbody>
                            </table>
                            <span class="spanEcrireDate"><?= $displayedMonth->get(Zend_Date::MONTH_NAME.' '.Zend_Date::YEAR); ?></span>
                        </div>
                        <?php $displayedMonth->addMonth(1); ?>
                    <?php endfor; ?>
                    <input type="hidden" id="hdnDates" name="hdnDates" class="" />
                    </div>
                </div>
                <div id="inputDatepicker">
                    <p style="font-style:italic; font-size:11px; font-weight:normal">
                        Entrez la date de l'évènement au format jj/mm/aaaa (p.ex. 01/10/2013)
                    </p>
                    <div class="calendar" style="margin-bottom: 20px; position: static;">
                        <input type="text" id="txtDates" name="txtDates" class="date" />
                    </div>
                </div>
                <?php
                /*
                 * Commentaire
                 */
                ?>
                <div id="commentaireEvenement">
                    <div style="margin-left:0px; width:300px">
                        <div class="totalBox">
                            <div class="box">
                                <h3 class="titreNews">Commentaire (facultatif)</h3>
                                <textarea style="font-size:12px;" id="CommentaireEvent" 
                                          name="commentaireEvent" tabindex="4" 
                                          cols="35" rows="8"><?= $this->evenement->getDescription(); ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div style="text-align:right">
                    <input type="reset" id="resetDate" class="bouton1" value="Remise à zéro" />
                    <input type="submit" id="validerDate" class="bouton1" style="padding:8px 5px; font-size:14px" value="Valider l'évènement" />
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Formulaire ajout/modif Type -->
<div id="divFormActionType" style="display:none">
    <form id="formActionType" method="post" action="<?= $this->url(array('controller' => 'type-event', 'action' => 'update')); ?>">
        <div id="titreNewType" class="bouton2 dataForm">
            <label for="type_nom" style="font-size:12px;  padding:0 10px 0 3px">Nom&nbsp;:</label>
            <input type="text" id="type_nom" name="type_nom" class="inputStyle" />
        </div>
        <div class="bouton2 dataForm">
            <label for="color" style="font-size:12px;  padding:0 10px 0 3px">Couleur&nbsp;:</label>
            <input type="color" id="color" name="color" class="inputStyle" value="#FF0000" />
        </div>
        <input type="hidden" id="idType_event" name="idType_event" />
    </form>
</div>
<!-- Fin formulaire ajout/modif Type -->
<div id="dialog" style="display: none;"></div>
