<?php if ($this->isAdmin()) {
    echo $this->partial('calendrier/_menuAdmin.phtml', array('action' => 'index'));
} ?>

<div id="selectDate">
    <?php $this->datePicker->setAction($this->url()); ?>
    <form id="selection" action="<?= $this->datePicker->getAction(); ?>" method="<?= $this->datePicker->getMethod(); ?>">
        <div class="bouton2">
            <?= $this->datePicker->mois->renderViewHelper(); ?>
            <?= $this->datePicker->annee->renderViewHelper(); ?>
        </div>
        <?= $this->datePicker->submit->renderViewHelper(); ?>
    </form>
</div>


<div id="globCalendar">
    <div id="nextPrevMonth">
        <?php
        $previousMonth = new Zend_Date($this->displayedMonth);
        $previousMonth->subMonth(1);
        ?>
        <a href="<?=
        $this->url(array(
            'mois' => $previousMonth->get(Zend_Date::MONTH),
            'annee' => $previousMonth->get(Zend_Date::YEAR),
        ));
        ?>" id="prevDate" class="bouton1">
            &lt;&lt; Mois précédent
        </a>
        <span id="texteMoisCourant">
            <?= ucwords($this->escape($this->displayedMonth->get(Zend_Date::MONTH_NAME.' '.Zend_Date::YEAR))); ?>
        </span>
        <?php
        $nextMonth = new Zend_Date($this->displayedMonth);
        $nextMonth->addMonth(1);
        ?>
        <a href="<?=
        $this->url(array(
            'mois' => $nextMonth->get(Zend_Date::MONTH),
            'annee' => $nextMonth->get(Zend_Date::YEAR),
        ));
        ?>" id="nextDate" class="bouton1">
            Mois suivant &gt;&gt;
        </a>
    </div>
    <!-- Zone dans lequel se trouve le calendrier -->
    <div id="datepicker">
        <div class="calendar">
            <table cellpadding="2">
                <thead>
                    <?php $jours = array('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche') ?>
                    <tr class="calendar">
                        <?php $nbJours = count($jours) ?>
                        <?php for ($i = 0; $i < $nbJours; $i++): ?>
                            <?php $class = ($i >= $nbJours - 2) ? 'weekendDay' : '' ?>
                            <td class="day <?= $class ?>">
                                <?php echo $jours[$i] ?>
                            </td>
                        <?php endfor ?>
                    </tr>
                </thead>
                <?php $nbJoursMois = $this->displayedMonth->get(Zend_Date::MONTH_DAYS); ?>
                <tbody>
                    <?php
                    $jourCourant = new Zend_Date($this->displayedMonth);
                    for ($i = 0; $i < $nbJoursMois; $i++):
                        // Si jourCourant est lundi
                        if (ucwords($jourCourant->get(Zend_Date::WEEKDAY)) == $jours[0]):
                            ?>
                            <tr>
                                <?php
                            endif;
                            // Création des cases vides de début de mois 
                            if ($i == 0):
                                ?>
                            <tr>
                                <?php
                                $dayOfWeeks = ($jourCourant->get(Zend_Date::WEEKDAY_DIGIT) + $nbJours - 1) % $nbJours;
                                for ($j = 0; $j < $dayOfWeeks; $j++):
                                    ?>
                                    <td class="calendarVide">&nbsp;</td>
                                    <?php
                                endfor;
                            endif
                            ?>
                            <?php
                            if (isset($this->evenements[$jourCourant->getIso()])) {
                                $events = $this->evenements[$jourCourant->getIso()];
                            } else {
                                $events = null;
                            }
                            ?>
                            <td 
                                title="<?= $jourCourant->get(Zend_Date::DAY.'/'.Zend_Date::MONTH.'/'.Zend_Date::YEAR) ?>" 
                                class="calendar defaultCalendar <?= (is_null($events)) ? '' : "selected" ?>">
                                    <?php if (is_null($events)): ?>
                                    <div class="day">
                                        <?= $jourCourant->get(Zend_Date::DAY) ?>
                                    </div>
                                <?php else: ?>
                                    <table>
                                        <tbody>
                                            <?php foreach ($events as $event): ?>
                                                <tr>
                                                    <td class="calendar eventSelected selected outSelected"
                                                        style="background-color: <?= $this->escape($event->type->color); ?>; border-color: <?= $this->escape($event->type->color); ?>;"
                                                        id="Event<?= $this->escape($event->id); ?>">
                                                        <div class="divNomEvent"><?= $this->escape($event->titre); ?></div>
                                                        <div><?= $jourCourant->get(Zend_Date::DAY); ?></div>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                <?php endif; ?>
                            </td>
                            <?php
                            // Création des cases vides de fin de mois 
                            if ($i == $nbJoursMois - 1):
                                $dayOfWeeks = $jourCourant->get(Zend_Date::WEEKDAY_DIGIT);
                                if ($dayOfWeeks != 0):
                                    for ($j = 0; $j < $nbJours - $dayOfWeeks; $j++):
                                        ?>
                                        <td class="calendarVide">&nbsp;</td>
                                    <?php endfor;
                                endif;
                                ?>

                            </tr>
                            <?php
                        endif;
                        // Si jourCourant est dimanche
                        if (ucwords($jourCourant->get(Zend_Date::WEEKDAY)) == $jours[$nbJours - 1]):
                            ?>
                            </tr>
                        <?php endif; ?>

                        <?php
                        $jourCourant->addDay(1);
                    endfor;
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<?php // Génération de la légende dont les types d'évènements existe le mois affiché.   ?>
<div class="totalBox" id="legende">
    <div class="box">
        <div class="titreNews">Légende :</div>
        <?php $margin = 0 ?>
<?php foreach ($this->legend as $l): ?>
            <div id="lgd<?= $this->escape($l->id) ?>" class="lgdElement" style="margin-left:<?= $margin ?>px;">
                <img src="/images/headerWTransparent.png" style="background-color:<?= $this->escape($l->color) ?>;"/>
                <span><?= $this->escape($l->nom) ?></span>
            </div>
            <?php $margin = 10; ?>
<?php endforeach; ?>
    </div>
</div>


<?php // Génération du récapitulatif    ?>
<div id="globalRecap">
    <div id="accordionCal">
        <h4 class="header titreSaison">
            Récapitulatif des évènements du mois de <?= $this->escape($this->displayedMonth->get(Zend_Date::MONTH_NAME)) ?> <?= $this->escape($this->displayedMonth->get(Zend_Date::YEAR)) ?>
        </h4>
        <div id="boiteRecap" class="box2">
            <?php foreach ($this->evenements as $events): ?>
            <?php foreach ($events as $event): ?>
                <div class="printInfo" id="recapEvent<?= $this->escape($event->id) ?>">
                    <span class="dateMiniTab">
                        <?= $this->escape(ucfirst($event->date->get(Zend_Date::WEEKDAY))) ?> 
                        <?= $this->escape($event->date->get(Zend_Date::DATE_LONG)) ?>
                    </span>
                    <table style="border-color:<?= $this->escape($event->type->color) ?>">
                        <tr>
                            <td class="print">Nom</td>
                            <td><?= $this->escape($event->titre) ?></td>
                        </tr>
                        <tr>
                            <td class="print">Type</td>
                            <td><?= $this->escape($event->type->nom) ?></td>
                        </tr>
                        <tr>
                            <td class="print">Lieu</td>
                            <?php if (is_string($event->lieu)): ?>
                                <td><?= $this->escape($event->lieu) ?></td>
                            <?php else: ?>
                                <td><?= $this->escape($event->lieu->nom) ?></td>
                        <?php endif; ?>
                        </tr>
                        <?php if ($event->horaire_debut != ''): ?>
                            <tr>
                                <td class="print">Début</td>
                                <td><?= $this->escape($event->horaire_debut) ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($event->horaire_fin != ''): ?>
                            <tr>
                                <td class="print">Fin</td>
                                <td><?= $this->escape($event->horaire_fin) ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($event->description != ''): ?>
                            <tr>
                                <td class="print">Commentaire</td>
                                <td><?= $this->escape($event->description); ?></td>
                            </tr>
                        <?php endif; ?>
                    </table>
                </div>
            <?php $event->date->addDay(1); ?>
            <?php endforeach ?>
            <?php endforeach ?>
        </div>
    </div>
    <?php
    /*
     * TODO Support des deux boutons suivants
     */
    /* <span>
      <span id="pdfCalendar" class="bouton1">Version pdf</span>
      <?php // Faire ce bouton via un appel à une action et pas tout faire en JS...    ?>
      <span id="printCalendar" class="bouton1">Version imprimable</span>
      </span>
      <form id="formPdfCalendar" method="post" action="">
      <input type="hidden" name="mois_pdf" value="<?php echo 'mois' ?>"/>
      <input type="hidden" name="annee_pdf" value="<?php echo 'année' ?>"/>
      <input type="hidden" name="date1" value="<?php echo 'date1' ?>"/>
      <input type="hidden" name="date2" value="<?php echo 'date2' ?>"/>
      </form> */
    ?>
</div>


