<?php //Si admin alors afficher des trucs ?>
<!-- Sous-menu de la categorie Calendrier -->
<div id="menuSelectionCat">
</div>
<?php // Fin de si admin ?>

<div style="text-align:center; margin-top:15px;">
    <?php //form a faire avec Zend ?>
    <div class="bouton2" style="display:inline; position:relative; z-index:5; padding:5px">
        <select name="inputMois">
            <?php for($i = 1; $i <= 12; $i++): ?>
            <option><?php echo $i; ?></option>
            <?php endfor ?>
        </select>
        <select name="inputAnnee">
            <?php for($i = 2008; $i < date('Y') + 2; $i++): ?>
            <option><?php echo $i; ?></option>
            <?php endfor ?>
        </select>
        <input style="padding:1px; margin-left:5px; font-size:10px" type="submit" value="Valider" />
    </div>
</div>


<div id="globCalendar">
<?php 
    $previousMonth = new Zend_Date($this->displayedMonth);
    $previousMonth->subMonth(1);
?>
    <a href="<?php echo $this->url(array(
            'mois' => $previousMonth->get(Zend_Date::MONTH),
            'annee' => $previousMonth->get(Zend_Date::YEAR),
        )) ?>" style="font-size:10px" id="prevDate" class="bouton1">
        &lt;&lt; Mois précédent
    </a>
    <span style="font-size:14px; font-weight:bold; margin:0px 130px" id="textMoisCourant">
            <?php echo ucwords($this->displayedMonth->get(Zend_Date::MONTH_NAME.' '.Zend_Date::YEAR)) ?>
    </span>
<?php 
    $nextMonth = new Zend_Date($this->displayedMonth);
    $nextMonth->addMonth(1);
?>
    <a href="<?php echo $this->url(array(
            'mois' => $nextMonth->get(Zend_Date::MONTH),
            'annee' => $nextMonth->get(Zend_Date::YEAR),
        )); ?>" style="font-size:10px" id="nextDate" class="bouton1">
        Mois suivant &gt;&gt;
    </a>
    <!-- Zone dans lequel se trouve le calendrier -->
    <div id="datepicker">
        <div class="calendar">
            <table cellpadding="2">
                <thead>
                    <?php $jours = array('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche') ?>
                    <tr class="calendar">
                        <?php $nbJours = count($jours) ?>
                        <?php for ($i = 0; $i < $nbJours; $i++): ?>
                        <?php $style = ($i >= $nbJours - 2)?'color:#d72c2c;':'' ?>
                        <td style="<?php echo $style ?>">
                            <?php echo $jours[$i] ?>
                        </td>
                        <?php endfor ?>
                    </tr>
                </thead>
                <?php $nbJoursMois = $this->displayedMonth->get(Zend_Date::MONTH_DAYS); ?>
                <tbody>
<?php 
    $jourCourant = $this->displayedMonth;
    for ($i = 0; $i < $nbJoursMois; $i++): 
        // Si jourCourant est lundi
        if (ucwords($jourCourant->get(Zend_Date::WEEKDAY)) == $jours[0]): ?>
                    <tr>
<?php   endif;
        // Création des cases vides de début de mois 
        if ($i == 0): ?>
                    <tr>
<?php       $dayOfWeeks = ($jourCourant->get(Zend_Date::WEEKDAY_DIGIT) + $nbJours - 1) % $nbJours; 
            for($j = 0; $j < $dayOfWeeks; $j++): ?>
                        <td class="calendarVide">&nbsp;</td>
<?php
            endfor;
        endif ?>
                        <td 
                            title="<?php echo $this->displayedMonth->get(Zend_Date::DAY.'/'.Zend_Date::MONTH.'/'.Zend_Date::YEAR) ?>" 
                            class="calendar defaultCalendar"
                            style="width:96px; height:50px;">
                            <div style="margin-top:2px; text-align: center; font-size:10px;">
                                <?php echo $this->displayedMonth->get(Zend_Date::DAY) ?>
                            </div>
                        </td>
<?php
        // Création des cases vides de fin de mois 
        if ($i == $nbJoursMois - 1):
            $dayOfWeeks = $jourCourant->get(Zend_Date::WEEKDAY_DIGIT);
            for($j = 0; $j < $nbJours - $dayOfWeeks; $j++):?>
                        <td class="calendarVide">&nbsp;</td>
<?php       endfor;?>
                    </tr>
<?php   endif;
        // Si jourCourant est dimanche
        if (ucwords($jourCourant->get(Zend_Date::WEEKDAY)) == $jours[$nbJours - 1]): ?>
                    </tr>
<?php   endif; ?>
                    
<?php 
        $jourCourant->addDay(1);
    endfor; 
?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<?php // Génération de la légende avec les types d'évènements donnés par la requête ?>
<div class="totalBox" id="legende" style="height:70px">
    <div class="box" style="float:right;">
        <div class="titreNews">Légende :</div>
        <div id="lgd<?php echo 'id' ?>" style="display:inline; margin-left:<?php echo '0' ?>">
            <img src="/images/headerWTransparent.png" style="background-color:blue; width:15px; height:12px;" />
            <span style="font-size:10px"><?php echo 'nom_evenement' ?></span>
        </div>
    </div>
</div>


<?php // Génération du récapitulatif ?>
<div id="globalRecap" style="width:500px; margin:0 auto; margin-top:10px">
    <div id="accordionCal">
        <h4 class="header titreSaison">
            Récapitulatif des évènements du mois de <?php echo 'mois' ?> <?php echo 'année' ?>
        </h4>
        <div id="boiteRecap" class="box2">
            <?php foreach($this->evenements as $evenement): ?>
            <div class="printInfo">
                <span class="dateMiniTab">
                    <?php echo $evenement['jour'] ?> <?php echo $evenement['date'] ?>
                </span>
                <?php $nePlusAfficher = array('jour', 'date') ?>
                <table style="border-style:solid; border-width:2px; border-color:<?php echo 'blue' ?>">
                    <?php foreach($evenement as $label => $contenu): ?>
                    <?php if (in_array($label, $nePlusAfficher)) {continue;} ?>
                    <tr>
                        <td class="print"><?php echo $label ?></td>
                        <td><?php echo $contenu ?></td>
                    </tr>
                    <?php endforeach ?>
                </table>
            </div>
            <?php endforeach ?>
        </div>
    </div>
    <span style="float:right">
        <span id="pdfCalendar" class="bouton1">Version pdf</span>
        <?php // Faire ce bouton via un appel à une action et pas tout faire en JS... ?>
        <span id="printCalendar" class="bouton1">Version imprimable</span>
    </span>
    <form id="formPdfCalendar" method="post" action="">
        <input type="hidden" name="mois_pdf" value="<?php echo 'mois' ?>"/>
        <input type="hidden" name="annee_pdf" value="<?php echo 'année' ?>"/>
        <input type="hidden" name="date1" value="<?php echo 'date1' ?>"/>
        <input type="hidden" name="date2" value="<?php echo 'date2' ?>"/>
    </form>
</div>


