<?php 
	$title = 'Delete an album';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure you want to delete '<?php echo $this->escapeHtml($album->nom); ?>'?</p>
<?php 
	$url = $this->url('album', array(
		'action' => 'delete',
		'id' => $this->id,
	));
?>
<form action="<?php echo $url ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->id ?>" />
		<input type="submit" name="del" value="Yes" />
		<input type="submit" name="del" value="No" />
	</div>
</form>