<div id="globalContent">
<!-- div du menu -->
<?php echo $this->partial('_sidebar.phtml', array('sections' => $this->sections, 'id' => $this->ultimate->id, 'controller' => $this->controller)) ?>
<!-- div du contenu de la page -->
    <div class="box" id="news">
        <div class="titreNews"><span><?= $this->escape($this->ultimate->titre); ?></span></div>
        <div class="contenuNews">
            <div><?= $this->ultimate->contenu ?></div>
        </div>
    </div>
</div>
<?php //Javascript chelou ?>
