<div style="margin-bottom:100px">
    <!-- div du menu -->
    <?php echo $this->partial('ultimate/_sidebar.phtml', array('sections' => $this->sections, 'id' => $this->id)) ?>
    <!-- div du contenu de la page -->
    <div class="box" id="content">
        <div class="titreNews"><span><?php echo $this->escape($this->ultimate['titre']); ?></span></div>
        <div style="margin-bottom:20px">
            <div><?php echo $this->escape($this->ultimate['contenu']) ?></div>
        </div>
    </div>
</div>
<?php //Javascript chelou ?>
