<ul id="menuDrop" class="apple">
    <?php foreach ($this->container as $page): ?>
        <li>
            <?php
            if ($page->isActive(true)) {
                $page->setClass('selected');
            }
            echo $this->menu()->htmlify($page);
            ?>
        </li>
    <?php endforeach ?>
</ul>
<script type="text/javascript">
    $(document).ready(function() {
        $("#menuDrop").dropmenu();
        $("#menuDrop").fadeTo(0,1);
    });
</script>
