<?php echo $this->doctype()."\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
<?php if ($this->doctype()->isRdfa()): ?>
          xmlns:og="http://opengraphprotocol.org/schema/"
          xmlns:fb="http://www.facebook.com/2008/fbml"
      <?php endif ?>
      >
    <head>
        <?= $this->headMeta()."\n" ?>
        <?= $this->headTitle()."\n" ?>
        <?= $this->headScript()."\n" ?>
        <?php if (Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->hasMessages()): ?>
            <script type="text/javascript">
                $(document).ready(function() {
            <?php foreach (Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->getCurrentMessages() as $message): ?>
                    displayFlash("<?= $this->escape($message) ?>");
            <?php endforeach; ?>
            });
            </script>
        <?php endif; ?>
        <?= $this->headLink()."\n" ?>
    </head>
    <body>
        <!-- Header : Bandeau logo -->
        <div id="bandeau1" class="bandeau">
            <div>
                <a href="http://www.sucstrasbourg.com/"><img src="/images/suc_logo.png" title="SUC Strasbourg" alt="SUC Strasbourg" id="sucLogo" /></a>
                <a href="<?php echo $this->baseUrl('/'); ?>"><img src="/images/minilogo.png" alt="Sesquidistus" id="sesquiLogo"/></a>
                <?php if (!is_null($this->user)): ?>
                    <a href="<?= $this->url(array('controller' => 'user', 'action' => 'index')) ?>">
                        <img class="avatar" src="<?= $this->user->profil->avatarMiniPath; ?>" alt="Photo <?= $this->user->login ?>" title="Espace Membre de <?= $this->user->login ?>" />
                    </a>
                    <span class="userLogin">
                        <a class="white2" href="<?= $this->url(array('controller' => 'user', 'action' => 'index')) ?>">
                            <?= $this->user->login ?>
                        </a>
                    </span>
                    <span class="userInfo">
                        <?php /* TODO 
                          <a class="white" href="?categorie=forum">Forum</a>
                          | */ ?>
                        <a class="white" href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout')) ?>">Déconnexion</a>
                    </span>
                <?php else: ?>
                    <span id="statutLog">
                        <a class="white" href="">Créer un compte</a>
                        | 
                        <a class="white" href="<?= $this->url(array('controller' => 'auth', 'action' => 'login')); ?>">S'identifier</a>
                    </span>
                <?php endif; ?>
            </div>
        </div>
        <!-- Menu style apple -->
        <div id="barreMenu">
            <?php echo $this->navigation()->menu()->setPartial('_nav.phtml'); ?>
        </div>

        <!-- Gallerie sous menu -->
        <div id="gallery">
        </div>


        <div id="globalBox">
            <?php echo $this->layout()->content."\n"; ?>
        </div>


        <!-- Footer -->
        <div id="footerPage">
            <img src="/images/silhouette.png" alt="Frisbee dive" id="footerDive" />
            <div id="bandeau2" class="bandeau">
                <img src="/images/minilogo2B.png" alt="Logo Sesquidistus"/>
                <span id="copyright">
                    Copyright ©<?php echo $this->escape($this->fromYear.' - '.$this->nowYear) ?> Sesquidistus
                </span>
                <div>
                    <a class="white" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'apropos')) ?>">&Agrave; propos du site</a> | 
                    <a class="white" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'mentions')) ?>">Mentions légales</a>
                </div>
            </div>
        </div>
    </body>
</html>

