<?= $this->doctype() . "\n" ?>
<html lang="fr" xmlns="http://www.w3.org/1999/xhtml"
<?php if ($this->doctype()->isRdfa()): ?>
    prefix="og: http://ogp.me/ns#"
    xmlns:fb="http://www.facebook.com/2008/fbml"
<?php endif ?>
>
    <head>
        <?= $this->headMeta() . "\n" ?>
        <?= $this->headTitle() . "\n" ?>
        <?= $this->headScript() . "\n" ?>
        <?php if (count($this->flashMessages) > 0): ?>
            <script type="text/javascript">
                $(document).ready(function() {
            <?php foreach ($this->flashMessages as $message): ?>
                displayFlash("<?= $this->escape($message) ?>");
            <?php endforeach; ?>
                });
            </script>
        <?php endif; ?>
        <?= $this->headLink() . "\n" ?>
    </head>
    <body>
        <!-- Header : Bandeau logo -->
        <header id="bandeau1" class="bandeau">
            <div>
                <a href="http://www.sucstrasbourg.com/"><img src="/images/suc_logo.png" title="SUC Strasbourg" alt="SUC Strasbourg" id="sucLogo" /></a>
                <a href="<?= $this->baseUrl('/'); ?>"><img src="/images/minilogo.png" alt="Sesquidistus" id="sesquiLogo"/></a>
                <?php if (!is_null($this->user)): ?>
                    <a href="<?= $this->url(array('controller' => 'user', 'action' => 'index'), null, true) ?>">
                        <img class="avatar" src="<?= $this->user->profil->avatarMiniPath; ?>" alt="Photo <?= $this->user->login ?>" title="Espace Membre de <?= $this->user->login ?>" />
                    </a>
                    <span class="userLogin">
                        <a class="white2" href="<?= $this->url(array('controller' => 'user', 'action' => 'index'), null, true) ?>">
                            <?= $this->user->login ?>
                        </a>
                    </span>
                    <span class="userInfo">
                        <a class="white" href="http://forum.frisbee-strasbourg.net/"><?php echo $this->translate->_('forum'); ?></a>
                        <a class="white" href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout')) ?>"><?php echo $this->translate->_('deconnexion'); ?></a>
                    </span>
                <?php else: ?>
                    <span id="statutLog">
                        <a class="white" href="<?= $this->url(array('controller' => 'user', 'action' => 'create')); ?>"><?php echo $this->translate->_('creer_compte'); ?></a>
                        | 
                        <a class="white" href="<?= $this->url(array('controller' => 'auth', 'action' => 'login')); ?>"><?php echo $this->translate->_('identifier'); ?></a>
                    </span>
                <?php endif; ?>
                <span id="change_language">
                	<a href="<?php echo $this->url(array('controller' => 'autre', 'action' => 'changelang', 'lang' => 'fr')); ?>">
                		<img alt="Français" src="/images/drapeau/drapeau-francais.png" />
                	</a>
                	<a href="<?php echo $this->url(array('controller' => 'autre', 'action' => 'changelang', 'lang' => 'en')); ?>">
                		<img alt="English" src="/images/drapeau/drapeau-anglais.png" />
                	</a>
                </span>
            </div>
        </header>
        <!-- Menu style apple -->
        <nav id="barreMenu">
            <?= $this->navigation()->menu()->setPartial('_nav.phtml'); ?>
        </nav>

        <!-- Bandeau défilant de photos -->
        <div id="bandeauDefilant">
            <?php if ($this->isAdmin()): ?>
                <a href="<?= $this->url(array('controller' => 'galerie', 'action' => 'bandeau'), null, true); ?>" class="bouton1">
                    Modifier
                </a>
            <?php endif; ?>
        </div>
        <script type="text/javascript">
<?php
for ($i = 0; $i < count($this->imagesBandeau); $i++) {
    $this->imagesBandeau[$i] = "'" . addslashes($this->imagesBandeau[$i]) . "'";
}
?>
    $(document).ready(function() {
        slideshow(new Array(<?= join(',', $this->imagesBandeau); ?>));
    });
        </script>

        <!-- div id="leftHeadBand">
            <img src="<?= $this->ad ?>" alt="15 ans des Sesquidistus" 
                 title="15 ans des Sesquidistus" />
        </div-->

        <div id="globalBox">
            <?php echo $this->layout()->content . "\n"; ?>
        </div>
        
        <!-- div id="rightHeadBand">
            <img src="<?= $this->ad ?>" alt="15 ans des Sesquidistus" 
                 title="15 ans des Sesquidistus" />
        </div-->


        <!-- Footer -->
        <footer id="footerPage">
            <img src="/images/silhouette.png" alt="Frisbee dive" id="footerDive" />
            <div id="bandeau2" class="bandeau">
                <img src="/images/minilogo2B.png" alt="Logo Sesquidistus"/>
                <span id="copyright">
                    Copyright ©<?php echo $this->escape($this->fromYear . ' - ' . $this->nowYear) ?> Sesquidistus
                </span>
                <div>
                    <a class="white" href="<?php echo $this->url(array('controller' => 'autre', 'action' => 'apropos')) ?>"><?php echo $this->translate->_('a_propos'); ?></a> | 
                    <a class="white" href="<?php echo $this->url(array('controller' => 'autre', 'action' => 'mentions')) ?>"><?php echo $this->translate->_('mentions_legales'); ?></a>
                </div>
            </div>
        </footer>
    </body>
</html>

