<div id="globalContent">
    <!-- div du menu -->
    <nav>
    <?=
    $this->partial('_sidebar.phtml', array('sections' => $this->sections,
        'id' => $this->club->id,
        'controller' => $this->controller))
    ?>
    </nav>
    <!-- div du contenu de la page -->
    <section class="box" id="news">
        <h1 class="titreNews"><?= $this->escape($this->club->titre); ?></h1>
        <?php if ($this->club->id == 3): //Section l'équipe => Trombinoscope ?>
            <?= $this->partial('_trombi.phtml', array('everybody' => $this->everybody, 'nbPerLine' => 4)); ?>
        <?php else: ?>
            <div class="contenuNews">
                <div><?= $this->club->contenu ?></div>
                <?php if ($this->isAdmin()): ?>
                    <form method="POST" id="frmContent" action="<?= $this->url(array('controller' => 'club', 'action' => 'modifier')); ?>">
                        <textarea id="content" name="content"><?= $this->club->contenu ?></textarea>
                        <input type="hidden" id="title" name="title"/>
                        <input type="submit" value="Valider le contenu" class="bouton1" />
                    </form>
                <?php endif; ?>
            </div>
            <?php if ($this->club->id == 5): // Pour les lieux d'entrainement  ?>
                <?= $this->partial('lieu/_affiche.phtml', array('lieux' => $this->lieux)); ?>
                <?php if ($this->isAdmin()){
                    echo $this->partial('lieu/_action.phtml', array('lieux' => $this->lieux));
                } ?>
            <?php endif; ?>
        <?php endif; ?>
    </section>
    <?php if ($this->club->id != 3 && $this->isAdmin()): ?>
        <div id="modifContent">
            <input class="bouton1" type="button" value="Modifier le contenu" />
        </div>
    <?php endif; ?>
</div>
