<div id="globalContent">
    <!-- div du menu -->
    <?php echo $this->partial('_sidebar.phtml', array('sections' => $this->sections, 'id' => $this->club->id, 'controller' => $this->controller)) ?>
    <?php if ($this->club->id == 3): //Section l'équipe => Trombinoscope ?>
    A faire...
    <?php // TODO inclusion du trombinoscope ?>
    <?php elseif ($this->club->id == 5): // Section Lieux d'entraînement ?>
    <?php else: ?>
    <!-- div du contenu de la page -->
    <div class="box" id="news">
        <div class="titreNews"><span><?= $this->escape($this->club->titre); ?></span></div>
        <div class="contenuNews">
            <div><?= $this->club->contenu ?></div>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php //Javascript chelou pour l'admin ?>
