<div class="totalBox">
    <div class="box">
        <div class="titreNews">Création d'un compte</div>
        <form method="POST" action="<?= $this->url(array('controller' => 'user', 'action' => 'create')); ?>" id="createAccount">
            <table id="profil">
                <tr class="style1">
                    <th>Identifiant</th>
                    <td><input id="login" type="text" class="required" name="login" maxlength="25" /><em>*</em></td>
                </tr>
                <tr class="style2">
                    <th>Mot de passe</th>
                    <td><input id="passwd" type="password" class="required" name="passwd" maxlength="255" /><em>*</em></td>
                </tr>
                <tr class="style1">
                    <th>Confirmation du mot de passe</th>
                    <td><input id="passwd2" type="password" class="required" name="passwd2" maxlength="255" equalto="#passwd" /><em>*</em></td>
                </tr>
                <tr class="style2">
                    <th>Prénom</th>
                    <td><input id="prenom" type="text" class="required" name="prenom" maxlength="50" /><em>*</em></td>
                </tr>
                <tr class="style1">
                    <th>E-mail</th>
                    <td><input id="mail" type="text" class="email" name="mail" maxlength="100" /></td>
                </tr>
                <tr class="style2">
                    <th>Joueur depuis</th>
                    <td>
                        <select id="adhesion" name="adhesion">
                            <option selected="selected" value="">Sélectionnez une année&nbsp;:</option>
                            <?php for ($i = 1995; $i <= date('Y'); $i++): ?>
                                <option label="<?= $i ?>" value="<?= $i ?>"><?= $i ?></option>
                            <?php endfor; ?>
                        </select>
                    </td>
                </tr>
                <tr class="style1">
                    <th>Numéro</th>
                    <td><input id="numero" type="text" class="digits" name="numero" /></td>
                </tr>
                <tr class="style2"><td>&nbsp;</td><td>Les champs marqués d'une <em>*</em> sont obligatoires</td></tr>
            </table>
            <input type="submit" class="bouton1" value="S'inscrire" />
        </form>
    </div>
</div>