<div class="totalBox">
    <!-- Div édition du profil -->
    <div class="box">
        <div class="titreNews">Mon profil</div>
        <fieldset>
            <legend>&Eacute;dition du profil&nbsp;: </legend>
            <?php $this->profilForm->setAction($this->url()); ?>
            <form method="<?= $this->profilForm->getMethod(); ?>" action="<?= $this->profilForm->getAction(); ?>" id="editProfil">
                <table style="width:100%;">
                    <tr>
                        <td rowspan="6">
                            <img src="<?= Application_Model_Profil::getAvatarPath().$this->user->profil->avatar ?>" 
                                 title="Cliquez pour changez votre photo!" class="bouton4" alt="Ma photo" id="avatar" />
                        </td>
                    </tr>
                    <tr class="style1">
                        <th><?= $this->profilForm->login->renderLabel(); ?></th>
                        <td><?= $this->profilForm->login->renderViewHelper(); ?></td>
                        <?php
                        if ($this->profilForm->getElement('prenom')->hasErrors()) {
                            $this->profilForm->getElement('prenom')->setAttrib('class', 'error');
                        }
                        ?>
                        <th><?= $this->profilForm->prenom->renderLabel(); ?></th>
                        <td>
                            <?= $this->profilForm->prenom->renderViewHelper(); ?>
                            <?php foreach ($this->profilForm->prenom->getMessages() as $message): ?>
                                <label for="prenom" class="error"><?= $message ?></label>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php
                    if ($this->profilForm->getElement('mail')->hasErrors()) {
                        $this->profilForm->getElement('mail')->setAttrib('class', 'error');
                    }
                    ?>
                    <tr class="style2">
                        <th><?= $this->profilForm->mail->renderLabel(); ?></th>
                        <td>
                            <?= $this->profilForm->mail->renderViewHelper(); ?>
                            <?php foreach ($this->profilForm->mail->getMessages() as $message): ?>
                                <label for="mail" class="error"><?= $message ?></label>
                            <?php endforeach; ?>
                        </td>
                        <th><?= $this->profilForm->adhesion->renderLabel(); ?></th>
                        <td><?= $this->profilForm->adhesion->renderViewHelper(); ?></td>
                    </tr>
                    <tr class="style1">
                        <th><?= $this->profilForm->numero->renderLabel(); ?></th>
                        <td><?= $this->profilForm->numero->renderViewHelper(); ?></td>
                        <th></th>
                        <td></td>
                    </tr>
                </table>
                <?= $this->profilForm->submit; ?>
                <a href="<?= $this->url(array('action' => 'view', 'login' => $this->user->login)); ?>">
                    <input type="button" value="Visualiser mon profil existant" class="bouton1"/>
                </a>
            </form>
        </fieldset>
        <div class="help">
            <?php //TODO Doc   ?>
            <a href="/doc/doc_membres/doc_membre.html#changer_photo" target="_blank"><img src="/images/help.png" alt="aide"/></a>
        </div>
    </div>

    <br />

    <!-- Div du changement de mot de passe -->
    <div class="box">
        <div class="titreNews">Mot de passe</div>
        <fieldset>
            <legend>Changement du mot de passe&nbsp;:</legend>
            <form method="<?= $this->pwdForm->getMethod(); ?>" action="<?= $this->pwdForm->getAction(); ?>" id="editPwd">
                <table id="pwd">
                    <tr class="style1">
                        <th><?= $this->pwdForm->new_pwd->renderLabel(); ?></th>
                        <td><?= $this->pwdForm->new_pwd->renderViewHelper(); ?></td>
                    </tr>
                    <tr class="style2"> 
                        <th><?= $this->pwdForm->confirm_pwd->renderLabel(); ?></th>
                        <td><?= $this->pwdForm->confirm_pwd->renderViewHelper(); ?></td>
                    </tr>
                </table>
                <?= $this->pwdForm->submit; ?>
            </form>
        </fieldset>
    </div> 
    <div class="help">
        <a href="./doc/doc_membres/doc_membre.html#changer_mdp" target="_blank"><img src="/images/help.png" alt="aide"/></a>
    </div>
</div>