<div class="totalBox">
    <!-- Div edititon du profil -->
    <div class="box">
        <div class="titreNews">Mon profil</div>
        <fieldset>
            <legend>&Eacute;dition du profil&nbsp;: </legend>
            <?php $this->profilForm->setAction($this->url()); ?>
            <form method="<?= $this->profilForm->getMethod(); ?>" action="<?= $this->profilForm->getAction(); ?>">
                <table style="width:100%;">
                    <tr>
                        <td rowspan="6">
                            <img src="<?= Application_Model_Profil::getAvatarPath().$this->user->profil->avatar ?>" 
                                 title="Cliquez pour changez votre photo!" class="bouton4" alt="Ma photo" id="avatar" />
                        </td>
                    </tr>
                    <tr class="style1">
                        <th><?= $this->profilForm->login->renderLabel(); ?></th>
                        <td><?= $this->profilForm->login->renderViewHelper(); ?></td>
                        <th><?= $this->profilForm->prenom->renderLabel(); ?></th>
                        <td><?= $this->profilForm->prenom->renderViewHelper(); ?></td>
                    </tr>
                    <?php //Zend_Debug::dump($this->profilForm->getMessages()) ?>
                    <?php if ($this->profilForm->getElement('mail')->hasErrors()) {
                              $this->profilForm->getElement('mail')->setAttrib('class', 'error');
                    } ?>
                    <tr class="style2">
                        <th><?= $this->profilForm->mail->renderLabel(); ?></th>
                        <td><?= $this->profilForm->mail->renderViewHelper(); ?></td>
                        <th><?= $this->profilForm->adhesion->renderLabel(); ?></th>
                        <td><?= $this->profilForm->adhesion->renderViewHelper(); ?></td>
                    </tr>
                    <tr class="style1">
                        <th><?= $this->profilForm->numero->renderLabel(); ?></th>
                        <td><?= $this->profilForm->numero->renderViewHelper(); ?></td>
                        <th></th>
                        <td></td>
                    </tr>
                </table>
                <?= $this->profilForm->submit; ?>
                <a href="<?= $this->url(array('action' => 'view', 'login' => $this->user->login)); ?>">
                    <input type="button" value="Visualiser mon profil existant" class="bouton1"/>
                </a>
            </form>
        </fieldset>
        <div class="help">
            <?php //TODO Doc ?>
            <a href="/doc/doc_membres/doc_membre.html#changer_photo" target="_blank"><img src="/images/help.png" alt="aide"/></a>
        </div>
    </div>

    <br />

    <!-- Div du changement de mot de passe -->
    <?php
    //Div qui va nous servir pour la dialog de confirmation.
    echo '<div id="confirmation" title="Confirmation" style="display: none;">'.
    '<p>Etes-vous sur de vouloir modifier le mot de passe?</p>'.
    '</div>';
    ?>
    <div class="box">
        <div class="titreNews">Mot de passe</div>
        <fieldset>
            <legend>Changement du mot de passe:</legend>
            <form method="POST" id="pwd_form" action="./?categorie=actions_profil">
                <table id="pwd">
                    <tr class="style1">
                        <th><label for="old_pwd">Mot de passe actuel: </label></th><td><input type="password" id="old_pwd" name ="old_pwd" value="" ></td>
                    </tr>
                    <tr class="style2">
                        <th class="style2"><label for="new_pwd">Nouveau mot de passe: </label></th><td><input type="password" id="new_pwd" name="new_pwd" value="" ></td>
                    </tr>
                    <tr class="style1"> 
                        <th><label for="new_pwd_confirm">Confirmation: </label></th><td><input type="password" id="new_pwd_confirm" name="new_pwd_confirm" value="" ></td>
                    </tr>
                </table>
                <input type="hidden" value="maj_mdp" name="mode" />
                <input type="submit" value="Valider" class="bouton1" id="btn_valider"/>
            </form>
        </fieldset>
    </div> 
    <div class="help">
        <a href="./doc/doc_membres/doc_membre.html#changer_mdp" target="_blank"><img src="/images/help.png" alt="aide"/></a>
    </div>
</div>