<div class="totalBox">
    <div class="box">
        <h1 class="titreNews"><?php echo $this->translate->_('espace_membre'); ?>: <?php echo $this->translate->_('bienvenue'); ?> <?= $this->user->login ?> !</h1>
        <ul class="login">
            <li title="<?php echo $this->translate->_('accedez_profil'); ?>">
                <div class="rotate">
                    <a class="black" href="<?= $this->url(array('action' => 'editProfil')); ?>">
                        <img alt="Profil" src="/images/membres/profil.png"/><br/><?php echo $this->translate->_('profil'); ?>
                    </a>
                </div>
            </li>
            <li title="<?php echo $this->translate->_('accedez_trombinoscope'); ?>">
                <div class="rotate">
                    <a class="black" href="<?= $this->url(array('action' => 'list')); ?>">
                        <img alt="Trombi" src="/images/membres/membre.png"/><br/><?php echo $this->translate->_('trombi'); ?>
                    </a>
                </div>
            </li>
            <li title="<?php echo $this->translate->_('accedez_forum'); ?>">
                <div class="rotate"><a class="black" href="http://forum.frisbee-strasbourg.net/"><img alt="Forum" src="/images/membres/forum.png"/><br/><?php echo $this->translate->_('forum'); ?></a></div>
            </li>
            <?php /* TODO Galerie membre soumet photos+vidéos
              <li title="Accédez à la galerie">
              <div class="rotate"><a class="black" href="./?categorie=member_galerie"><img alt="Galerie" src="/images/membres/galerie.png"/><br/>Galerie</a></div>
              </li> */ ?>
            <?php /*
              <li title="Accédez à la page de sondage">
              <div class="rotate">
              <a class="black" href="./?categorie=sondage'.$tabSondage[0].'">
              <img alt="Sondage" src="./images/membres/sondage.png"/>
              <span style="position:absolute; margin-left:-20px" class="'.$classBulle.'">'.count($tabSondage).'</span><br/>Sondage
              </a>
              </div>
              </li> */ ?>
        </ul>
        <p>[<a class="black" href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>"><?php echo $this->translate->_('deconnexion'); ?></a>]</p>
    </div>
</div>