<div class="totalBox">
    <div class="box">
        <h1 class="titreNews">
            Feuille profil membre
            <?php if ($this->isAdmin()): ?>
                <a href="<?= $this->url(array('controller' => 'user', 'action' => 'supprimer', 'id' => $this->member->id)); ?>" class="supprimer">
                    <img class="editUser" src="/images/del.png" alt="Supprimer" title="Supprimer"/>
                </a>
            <?php endif; ?>
        </h1>
        <fieldset>
            <legend>Profil :</legend>
            <table id="profil">
                <tr>
                    <td rowspan="3">
                        <img id="avatar" src="<?= $this->member->profil->avatarPath ?>" 
                             class="bouton2" alt="Ma photo" />
                    </td>
                </tr>
                <tr class="style1">
                    <th>Login&nbsp;:</th>
                    <td id="login"><?= $this->escape($this->member->login); ?></td>
                    <th>Membre depuis&nbsp;:</th>
                    <?php $adhesion = $this->member->profil->adhesion; ?>
                    <td><?= $this->escape((!empty($adhesion))?$this->member->profil->adhesion->get(Zend_Date::YEAR):''); ?></td>
                </tr>
                <tr class="style2">
                    <?php /* TODO On affiche l'e-mail ? C'est une page public. 
                     * Ou alors juste pour les gens connecté ?
                      <th>E-mail&nbsp;:</th>
                      <td><?= $this->member->profil->mail; ?></td>
                     */ ?>
                    <th>Prénom&nbsp;:</th>
                    <td><?= $this->escape($this->member->profil->prenom); ?></td>                    
                    <th>Numéro</th>
                    <td><?= $this->escape($this->member->profil->numero); ?></td>
                </tr>
                <?php if ($this->isAdmin()): ?>
                    <tr>
                        <td colspan="4"></td>
                        <td>
                            <a href="<?= $this->url(array('controller' => 'user', 'action' => 'editProfil')); ?>" class="bouton1">
                                Modifier
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
            </table>
        </fieldset>
    </div>
</div>

<div id="dialog" style="display:none;"></div>