<nav style="margin-bottom:25px">
    <a id="organiserButton" class="bouton1 <?= ($this->type == 5) ? 'boutonPageCourante' : ''; ?>" href="<?= $this->url(array('action' => 'index', 'type' => 5)); ?>">
        <?php echo $this->translate->_('evenements_club'); ?>
    </a>
    <a id="participerButton" class="bouton1 <?= ($this->type == 4) ? 'boutonPageCourante' : ''; ?>" href="<?= $this->url(array('action' => 'index', 'type' => 4)); ?>">
        <?php echo $this->translate->_('evenements_participe'); ?>
    </a>
    <a id="ffdfButton" class="bouton1 <?= ($this->type == 11) ? 'boutonPageCourante' : ''; ?>" href="<?= $this->url(array('action' => 'index', 'type' => 11)); ?>">
        <?php echo $this->translate->_('evenements_ffdf'); ?>
    </a>
</nav>

<section id="accordionEvent" style="margin-bottom:40px"> 
    <?php foreach ($this->evenements as $interval => $evenements): ?>
        <h4 class="header titreSaison"><?php echo $this->translate->_('evenements_saison'); ?> <?= $interval ?></h4>
        <div class="box2">
            <table class="table">
                <tr class="header">
                    <th><?php echo $this->translate->_('titre'); ?></th>
                    <th><?php echo $this->translate->_('lieu'); ?></th>
                    <th><?php echo $this->translate->_('date'); ?></th>
                    <th><?php echo $this->translate->_('contenu'); ?></th>
                </tr>
                <?php foreach ($evenements['evenements'] as $evenement): ?>
                    <tr class="mouseover">
                        <td><?= $evenement->titre ?></td>
                        <td><?= (is_string($evenement->lieu)) ? $evenement->lieu : $evenement->lieu->nom; ?></td>
                        <td><?= $evenement->date->get(Zend_Date::DATES) ?></td>
                        <td>
                            <?php if ($evenements['article'][$evenement->id]): ?>
                                <a href="<?= $this->url(array('controller' => 'index', 'type' => null, 'id_event' => $evenement->id)); ?>">
                                    <img style="cursor:pointer" id="ico<?= $evenement->id; ?>" src="/images/page.png" alt="Articles" title="<?php echo $this->translate->_('evenement_acceder_article'); ?>" />
                                </a>
                            <?php endif; ?>
                            <?php if ($this->isAdmin()): ?>
                                <a href="<?= $this->url(array('controller' => 'calendrier', 'action' => 'editer', 'type' => null, 'id_event' => $evenement->id)); ?>">
                                    <img style="cursor:pointer" id="icoModif<?= $evenement->id; ?>" src="/images/page2.png" alt="Modifier" title="Modifier l'évènement" />
                                </a>
                            <?php endif; ?>
                            <?php /* TODO mais ne semble pas terrible sur le précédent site...
                              <span>
                              <img style="cursor:pointer" id="icoPhoto<?= $evenement->id; ?>" src="/images/image.png" alt="Images" title="Images de l'évènement" />
                              </span>
                              <span>
                              <img style="cursor:pointer" id="icoVideo<?= $evenement->id; ?>" src="/images/film.png" alt="Video" title="Vidéos de l'évènement" />
                              </span> */ ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endforeach; ?>
</section>

