<div style="margin-bottom:25px">
    <a id="organiserButton" class="bouton1" href="<?= $this->url(array('action' => 'index')); ?>">&Eacute;vènements organisés par le club</a>
    <a id="participerButton" class="bouton1" href="<?= $this->url(array('action' => 'index')); ?>">&Eacute;vènements auxquels le club participe</a>
</div>

<div id="accordionEvent" style="margin-bottom:40px"> 
    <h4 class="header titreSaison">&Eacute;vènements de la saison<?= ' ...' ?></h4>
    <div class="box2">
        <table class="table">
            <tr class="header">
                <th>Titre</th>
                <th>Lieu</th>
                <th>Date</th>
                <th>Contenu</th>
            </tr>
            <?php foreach($this->evenements as $evenement): ?>
            <tr class="mouseover">
                <td><?= $evenement->titre ?></td>
                <td><?= $evenement->lieu ?></td>
                <td><?= $evenement->date->get(Zend_Date::DATES) ?></td>
                <td>
                    <span style="margin-right:5px;">
                        <img style="cursor:pointer" id="ico<?= $evenement->id; ?>" src="/images/page.png" alt="Articles" title="Accéder aux articles liés à cet évènement" />
                    </span>
                    <span style="margin-right:5px;">
                        <img style="cursor:pointer" id="icoPhoto<?= $evenement->id; ?>" src="/images/image.png" alt="Images" title="Images de l'évènement" />
                    </span>
                    <span style="margin-right:5px;">
                        <img style="cursor:pointer" id="icoVideo<?= $evenement->id; ?>" src="/images/film.png" alt="Video" title="Vidéos de l'évènement" />
                    </span>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>