<div id="globalMini">
    <div id="galerie" class="totalBox">
        <div class="box" style="min-height:150px;">
            <img style="position:absolute; right:2px; bottom:1px" src="/images/silhouette3_mini.gif" />
            <div class="titreNews">Photos & vidéos</div>
            <div style="text-align:left;"> 
                <div style="color:#bc0101; margin-bottom:10px; font-size:11px">Blabla</div>
            </div>
        </div>
    </div>
</div>

<div id="globalNews">
    <?php foreach ($this->articles as $article): ?>
        <?= $this->partial('article/_article.phtml', array('article' => $article)); ?>
    <?php endforeach; ?>
</div>